### PR TITLE
[ActionSheet] Have content positioned based on the layout margins of the container.

### LINKED ISSUE #7284: [ActionSheet] ActionSheet ignores the safe area inset in landspace
This was filed as an internal issue. If you are a Googler, please visit [b/131464786](http://b/131464786) for more details.

---
#### Internal data
- Associated internal bug: [b/131464786](http://b/131464786)
- Blocked by: https://github.com/material-components/material-components-ios/issues/7332

### PR DESCRIPTION
**Pull request by yarneo**
ActionSheet's content was not taking into regards the layout margins provided by the bottom sheet. In this PR I am having the constraints of the content look at the layout margin. Also, the ActionSheetController's view needs to preserve the superviews layout margins to correctly pass those margins to the UITableViewCells.
The same logic is also done for the action sheet's header view, to use layout margins.

Screenshots

|Before|After|
|---|---|
|Screen Shot 2019-05-02 at 3 09 33 PM|Screen Shot 2019-05-02 at 3 10 12 PM|
|Screen Shot 2019-05-02 at 3 09 22 PM|Screen Shot 2019-05-02 at 3 10 20 PM|

Resolves #7284

### CODE REVIEW

**Comment by yarneo** [comment]
Opened issue to add better snapshot testing for landscape for action sheet: https://github.com/material-components/material-components-ios/issues/7332

**Review by romoore — APPROVED** [review]

**Review by codeman7 — APPROVED** [review]
Thanks for the help!

**Comment by romoore** [comment]
The snapshot tests merged. Merging `develop` into this branch should show the snapshot test changes. 

Update: Whoops! I just saw they were already merged.  From what I can see in the images, it appears the safeAreaInsets aren't fully respected. I'm not sure if that's related to this PR, but it's worth double-checking.

**Comment by jverkoey** [comment]
To confirm: was this tested on both iOS 11 and iOS 12?

**Comment by yarneo** [comment]
I am holding on merging this, pending a better solution that doesn't involve layoutMargins but rather understanding why the safeAreaInsets are not passed to the MDCDraggableView's subviews of the MDCBottomSheet.

**Review by jverkoey — COMMENTED** [review]
I can't quite tell but it looks like there's a few things going on here; can we break this PR up into smaller pieces?

**Comment by yarneo** [comment]
Unfortunately we can't because it all depends on one another. I'll bring this PR up in the daily so we can discuss next steps.

**Comment by jverkoey** [comment]
sgtm

**Pull request merged**
