### PR TITLE
[Examples/Tests] Convert @imports to imports

### PR DESCRIPTION
**Pull request by romoore**
In order to make the internal build systems happier, @import statements should not be used.

### CODE REVIEW

**Comment by ianegordon** [comment]
Let's chat on this tomorrow.

**Review by randallli — APPROVED** [review]

**Comment by romoore** [comment]
This is necessary for both internal builds, but also for bazel builds on kokoro. In order for us to include building our examples (a very good thing) on Kokoro, we'll have to make this change until bazel supports modules imports.

**Comment by ianegordon** [comment]
Interesting.

**Review by ianegordon — COMMENTED** [review]
Acknowledged.  Let's make sure we open an issue with the Bazel team if there isn't one already.

**Review by ianegordon — APPROVED** [review]

**Pull request merged**
