### PR TITLE
[MDCPageControl] Fixes MDCPageControl not properly revealing page indicators.

### PR DESCRIPTION
**Pull request by yarneo**
-[MDCPageControl revealIndicatorsReversed:] was incorrectly computing the indicator index when the reversed flag was YES. The index is updated to accommodate the reversal flag, but the collection is still being enumerated in normal order. This makes the isCurrentPageIndicator check apply to the wrong indicator.

|Before|After|
|---|---|
|pc-rtl-bug|pcfix|

### CODE REVIEW

**Review by romoore — DISMISSED** [review]
Please add gifs showing the animation before and after.

**Comment by yarneo** [comment]
Please see cl/234610019 for gifs.

**Comment by romoore** [comment]
This bug is easily reproducible in our catalog - could you please include the gifs here in the PR summary?

**Comment by romoore** [comment]
Here's the "broken" version from develop:
pc-rtl-bug

**Comment by yarneo** [comment]
Fixed version:
fixedpagecontrol

**Comment by romoore** [comment]
lol, the "fixed" version is so big!

**Comment by yarneo** [comment]
The size is part of the fix :P

**Comment by romoore** [comment]
Looks like the fixed version isn't RTL? The bug isn't reproducible in LTR layouts, though.

**Comment by yarneo** [comment]
Put RTL "after" version in description to PR.

**Comment by romoore** [comment]
In the first frame of the "after" there's only one dot - is that present in the actual fix or some weird glitch in the gifs?

screen shot 2019-02-27 at 1 00 04 pm

**Comment by yarneo** [comment]
it's a GIF thing. Please check in your simulator if you believe that that's not the case. All 3 dots appear when I run the example on RTL.

**Review by romoore — APPROVED** [review]
Tested locally and the rendering issues from the gifs were not seen.

**Pull request merged**
