### PR TITLE
[ActivityIndicator] Migrated to MDFi18n.

### PR DESCRIPTION
**Pull request by sigito**
Partially addresses #1475.

### CODE REVIEW

**Review by ianegordon — DISMISSED** [review]
Excellent!

Please add MDFI18n as a dependency and remove private/RTL in the Podspec.  (Here and in the other migration PRs)

**Comment by sigito** [comment]
@ianegordon, I have updated a Podspec file in this PR only. Could you take a look if it's alright, so I would do the same in other and future RPs? 

Also, how could I catch a problem of not making these changes in a Podspec file? `pod update` worked OK and it built just fine in Xcode. Is there a different process to test pods configurations?

**Comment by ianegordon** [comment]
Hi @sigito  My understanding is that since one of our components pulls in MDFI18n (Dialogs), any of our components can use it since they are all pulled into the same project.  This would break if a client tried to pull in only ActivityIndicator, without Dialogs (and transitively MDFI18n).  Unfortunately I don't know of an easy test.  Perhaps in the future it would make sense to have a target for each component.

**Review by ianegordon — APPROVED** [review]

**Comment by ianegordon** [comment]
HI @sigito .  Thanks for putting this together.  Sorry for the delay, but I wanted to land the latest release of MDFI18n internally before merging this.

Your change to the podspec is exactly what we need for the other PRs.  Remove the ss.dependency on private/RTL and add a dependency on MDFInternationalization.  Can you make this change to the other PRs and I'll merge them as well?

**Pull request merged**
