### PR TITLE
[Chips] Create theming extension for Chips

### PR DESCRIPTION
**Pull request by rami-a**
### Context
As the team pivots to using theming within extensions we continue this work with Chips.

### The problem
We currently do not theme chips using a theming extension

### The fix
* Add theming extension for MDCChipView
* Write unit tests for new extension

In follow-up PRs, I will update the existing examples to utilize the new extension and write snapshot tests as well.

### Bug
Part of #6083

### CODE REVIEW

**Review by jverkoey — APPROVED** [review]
Yay!

**Comment by jverkoey** [comment]
Can we add some snapshot tests too?

**Comment by rami-a** [comment]
Good idea! I'd like to keep this PR as small as I can though, so I'll add snapshot tests in a follow up PR.

**Comment by jverkoey** [comment]
sgtm

**Review by romoore — DISMISSED** [review]

**Comment by romoore** [comment]
Oh sorry, I didn't know you didn't want my review. Let me take it off.

**Review by romoore — COMMENTED** [review]
Removing review.

**Comment by rami-a** [comment]
@romoore I think I just misunderstood the concept of the codeowners integration as requiring a review from that owner. Now I understand that it is for awareness. Feel free to still leave a review if you'd like (or had any concerns).

**Pull request merged**
