### PR TITLE
[Themer] Updating the protocol generic syntax.

### PR DESCRIPTION
**Pull request by willlarche**
Just to be more expected.

### CODE REVIEW

**Comment by ajsecord** [comment]
Big change—what's the benefit?

**Comment by willlarche** [comment]
The functionality doesn’t change at least. No code implementing these
functions needs to change.

The benefit is that this is a more expected API. When the api uses ‘id’,
the message to the developer is ‘this stands in for an object whose type is
unknown.’ But when the api used is ‘NSObject*’, the subtext is “I’m looking
for the type NSObject” which is specific and misleading. It could cause
someone to think twice about what they are doing and these are protocols we
want people to use. They shouldn’t hesitate. The new API matches the syntax
Apple, and the general community, and us in the majority of places, use.

Moreover, by making the protocol inherit from the NSObject, we are adhering
to a best practice.

From:
https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithProtocols/WorkingwithProtocols.html

It’s best practice to define your protocols to conform to the NSObject
protocol (some of the NSObject behavior is split from its class interface
into a separate protocol; the NSObject class adopts the NSObject protocol).

**Review by ajsecord — APPROVED** [review]

**Review by jgunaratne — APPROVED** [review]

**Review by romoore — APPROVED** [review]
Yes, please! I've wondered why we require the NSObject base class. :)

**Comment by ajsecord** [comment]
Build breakage is from #2400, not this PR...

**Pull request merged**
