### PR TITLE
Release candidate 40.1.0

### PR DESCRIPTION
**Pull request by jverkoey**

### CODE REVIEW

**Comment by ianegordon** [comment]
This PR seems,... uncommon?  Usually, after internal testing, we merge from release-candidate to stable and from release-candidate to develop and push the changes from the command line.

**Comment by jverkoey** [comment]
This PR is meant to target stable, but otherwise it follows https://github.com/material-components/material-components-ios/blob/develop/contributing/releasing.md#send-the-release-out-for-review

**Comment by ajsecord** [comment]
Ian's right, this should be diff'd off of stable

**Comment by jverkoey** [comment]
Re-opened in https://github.com/material-components/material-components-ios/pull/2526.

**Pull request closed without merging**
