### PR TITLE
[kokoro] Send build results to codecov after cocoapods invocation.

### PR DESCRIPTION
**Pull request by jverkoey**

### CODE REVIEW

**Review by ianegordon — APPROVED** [review]
As this code is already public, LGTM.

**Comment by ianegordon** [comment]
Please merge if the results are as expected.

**Comment by jverkoey** [comment]
Codecov is requiring that we provide the token as part of the build, so I've added that in cl/176010682.

**Comment by jverkoey** [comment]
Will re-run this PR once the environment variables are deployed.

**Comment by jverkoey** [comment]
Code coverage is now working, but codecov isn't picking up kokoro as a CI service because our context doesn't match their expected terminology. I'm deploying an update to our contexts now so that codecov will automatically send coverage reports once kokoro completes its runs.

**Comment by jverkoey** [comment]
codecov's expected naming conventions are documented here: https://docs.codecov.io/docs/detecting-ci-services

**Comment by willlarche** [comment]
Thank you!!

**Comment by jverkoey** [comment]
I expect that until we turn off travis CI that codecov won’t post updates because it waits until all ci services have completed.

**Pull request merged**
