### PR TITLE
[Banner] Add a missing button title in example.

### PR DESCRIPTION
**Pull request by fluxminds**
Closes https://github.com/material-components/material-components-ios/issues/8368.

A button is missing from the example. Note: these two buttons are not aligned well. To be fixed in https://github.com/material-components/material-components-ios/pull/8370.

| Before | After |
| --- | --- |
| Simulator Screen Shot - iPhone Xʀ - 2019-08-26 at 15 18 32 | Simulator Screen Shot - iPhone Xʀ - 2019-08-26 at 15 24 05 |

### CODE REVIEW

**Review by randallli — COMMENTED** [review]
why are the buttons not aligned in your snapshots after? "Long dismiss" is lower than "dismiss"

**Comment by fluxminds** [comment]
@randallli It is caused by MDCButton overwriting `sizeThatFits`, which causes it returns a different value than `instrinsicContentSize`. It will be fixed in separate PR as mentioned in the description. This PR mainly focuses on adding this button back.

**Review by randallli — APPROVED** [review]
whoops sorry didn't see that

**Comment by fluxminds** [comment]
Thanks for the review!

**Pull request merged**
