### PR TITLE
[Collections] fix markdown in styling readme

### PR DESCRIPTION
**Pull request by morganchen12**
No code changes included.

### CODE REVIEW

**Comment by willlarche** [comment]
Thanks for the pull request!

The divs are actually necessary for a parser we are hoping to use but there is definitely a couple mistakes you can correct:

- The divs should be wrapped in comments: 
- Swift snippets should be before Objective C snippets (in each coupling)

**Review by willlarche — CHANGES_REQUESTED** [review]
Consider changes mentioned in previous comment.

**Comment by morganchen12** [comment]
Done.

**Comment by willlarche** [comment]
Thanks!

I noticed you changed our ~~~ to ```. Is there a gain there?

**Comment by morganchen12** [comment]
No, I think they mean the same thing. I changed them because I didn't know you could tildes to delineate code blocks until now.

**Comment by willlarche** [comment]
Oh, ok! Do me a favor and change them back so they match the rest of our docs and we'll be good to merge.

**Comment by morganchen12** [comment]
Done.

**Review by willlarche — APPROVED** [review]
Thanks for fixing this doc!

**Pull request merged**
