### PR TITLE
[AppBar] Adds example using a UITableViewController with sections.

### PR DESCRIPTION
**Pull request by macourteau**
This example demonstrates issue #2032.

AppBarSectionHeadersExample.m is forked from AppBarTypicalUseExample.m.

#### Don't forget:
- [x] Identify the component the PR relates to in brackets in the title. ```[Buttons] Updated documentation```
- [x] Link to GitHub issues it solves. ```closes #1234```
- [x] Sign the CLA bot. You can do this once the pull request is submitted.

[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.

### CODE REVIEW

**Review by ianegordon — APPROVED** [review]
Tested locally in sim.

**Comment by ianegordon** [comment]
Thanks you @macourteau !

**Comment by ajsecord** [comment]
Hi @macourteau, did you sign the CLA for this commit? Could you please go to https://cla.developers.google.com/ and sign the CLA?

**Comment by jverkoey** [comment]
Oh...I wonder if you click the web merge button if it ends up pulling the author's Github email address for the squashed commit...

**Comment by ajsecord** [comment]
I have verified that @macourteau has effectively signed the CLA.

**Pull request merged**
