### PR TITLE
v54.11.1 (hotfix)

### PR DESCRIPTION
**Pull request by AlimoRabbani**

### CODE REVIEW

**Comment by romoore** [comment]
Did a client break?

**Comment by jverkoey** [comment]
This is a risky change so we are landing it as a hotfix in order to isolate its impact on the regular release.

**Comment by jverkoey** [comment]
Can you run `./scripts/release notes` and paste the content into the changelog please? This will ensure that your cherry-picked commit gets attributed correctly. When doing so please remove the auto-generated commits from the notes - we only want component-specific changes to appear in the changelog.

**Review by jverkoey — CHANGES_REQUESTED** [review]
Please run ./scripts/release notes and paste the content into the changelog.

This will ensure that your cherry-picked commit gets attributed correctly. When doing so please remove the auto-generated commits from the notes - we only want component-specific changes to appear in the changelog.

**Review by jverkoey — APPROVED** [review]
Cool. Please do not merge until internal testing is complete.

**Comment by jverkoey** [comment]
And also please do not merge using GitHub. Your workflow is now essentially:

- [x] Make an internal CL for the release, pointing to release-candidate. Remember that you will also have to point to your repo. If that doesn't work then push the release-candidate to this repo.
- [x] Run a global test on the CL.
- [x] Once the CL has been confirmed to pass all tests, let me know and I will merge the release candidate into stable/develop and push it to the main repo.
- [x] You can then re-sync your CL using the default settings. This will sync to the main repo's `stable` and update the metadata attached to the CL.
- [ ] Submit the CL.
- [ ] Once the CL is submitted, I will publish the release.

**Comment by AlimoRabbani** [comment]
Internal testing is done. We should now be ready to merge this into stable.

**Comment by jverkoey** [comment]
The release candidate has been merged to stable. Please re-sync your internal CL now using the default arguments.

Will publish the release once you confirm that the CL has landed.

**Comment by jverkoey** [comment]
Note: Please re-sync your internal CL now using the default arguments.

**Comment by AlimoRabbani** [comment]
The CL has landed.

**Pull request merged**
