### PR TITLE
[Collections] Make dismiss animation a simple swipe

### LINKED ISSUE #1833: [Collections] Arc animation during the swipe-to-dismiss gesture
### Overview
When using a swipe-to-dismiss gesture, the cells have an "arc" effect. This looks weird and there is small non-smooth animation just before the beginning of the rotation (the movement is: small translation, then rotation, then translation). This is much more visible on large screen (landscape iPhone for example).
Is it possible to remove the arc gesture or have an option to toggle it?

mdccell-swipe-dismiss

### Reproduction steps
Open the swipe-to-dismiss example on the catalog and swipe a cell.

### Version number
 - 31

### PR DESCRIPTION
**Pull request by romoore**
Dismissing a cell or section in a UICollectionView that uses an
MDCCollectionViewController with the default editor will now use a
simple linear dismiss animation.

### Original Animation
swipe-delete-orig

### New Animation
swipe-delete-new

Closes #1833

### CODE REVIEW

**Comment by romoore** [comment]
Marking blocked to allow internal clients time to review.

**Review by ajsecord — APPROVED** [review]

**Review by ianegordon — COMMENTED** [review]
Thank you for sending out the announcement.  Consider adding a comment in this thread with the expected merge date.

**Review by ianegordon — APPROVED** [review]

**Comment by romoore** [comment]
Assuming the next internal release is on Wednesday, this PR will be merged on Thursday, August 24.

**Comment by romoore** [comment]
This week's release (33.0.0) just went through. I will merge this PR tomorrow.

**Review by ajsecord — APPROVED** [review]

**Pull request merged**
