### PR TITLE
[ios8]! Drop support for iOS 8 in all components.

### LINKED ISSUE #4656: Drop support for iOS 8
Bump our minimum deployment target to iOS 9.1.
(To avoid an internationalization issues in iOS 9.0,  9.1 is will be the minimum)

---
#### Internal data
- Associated internal bug: [b/70785987](http://b/70785987)
- Blocked by: https://github.com/material-components/material-components-ios/issues/5509

### PR DESCRIPTION
**Pull request by jverkoey**
Closes https://github.com/material-components/material-components-ios/issues/4656

I used the following `grep` to find references to iOS 8:

    grep -rI "8\.0" .

### CODE REVIEW

**Comment by romoore** [comment]
Fixed the PR title to omit the incorrect "everything" component name.

**Review by romoore — APPROVED** [review]

**Comment by jverkoey** [comment]
Am using the `[ ]!` notation for the release script to pick this up as a breaking change.

**Review by yarneo — APPROVED** [review]

**Comment by yarneo** [comment]
@wenyuzhang666 FYI this is a breaking change for the next release

**Comment by romoore** [comment]
@jverkoey Is this a new process we should follow for breaking changes? This is the first I've heard of it.

**Comment by romoore** [comment]
@jverkoey Also, I believe this is not a breaking change according to SemVer 2.0.

**Comment by jverkoey** [comment]
This will fall under the category of "Any change that will result in a build breakage from the previous release." for any client that has a minimum deployment target < 9.0.

**Pull request merged**
