### PR TITLE
Revert "[TextFields] Preserve placeholder font."

### PR DESCRIPTION
**Pull request by bryanoltman**
Reverts material-components/material-components-ios#8444. This is being reverted because of an internal client issue. The client is addressing this issue and we should be able to put this change in our next release. This change is being reverted both in `develop` and in `release-candidate`

### CODE REVIEW

**Comment by romoore** [comment]
Shouldn't this be reverted in the release branch and then merged back to `develop`?

**Comment by jverkoey** [comment]
It comes down to the same end result, but in this case we can roll forward in develop sooner so it may be preferable to take this approach in general.

**Comment by romoore** [comment]
Either way, I don't believe we can roll-forward in `develop` until the revert from `release-candidate` is merged back to `develop`.

**Review by romoore — DISMISSED** [review]
I believe this should be reverted in the release branch rather than having to roll-up a brand new release branch.

**Comment by jverkoey** [comment]
> I believe this should be reverted in the release branch rather than having to roll-up a brand new release branch.

We aren't rolling up a new release branch. Please chat with Bryan directly to understand what's going on :)

**Comment by romoore** [comment]
Thanks, Jeff. @bryanoltman Could you please update the PR summary to explain more about the issue and why it's being reverted in `develop` rather than `release-candidate`?

**Pull request closed without merging**
