### PR TITLE
[BottomNavigation] Fix Item View layout.  

### PR DESCRIPTION
**Pull request by romoore**
Uses the [layout specifications from the Material Guidelines
article](https://material.io/design/components/bottom-navigation.html#specs)
to correctly lay out the item view. Of notable import, the label will
now be clipped if it would otherwise extend outside of the view's frame.
This allows the inter-item spacing to be preserved in
MDCBottomNavigationBar.

The previous layout of the Item View was incorrect. Rather than using
the entire view bounds efficiently, it was placing the icon at 20% from
the leading edge of the view, then placing the bounds (potentially)
outside the frame of the view.

Part of #6520

### CODE REVIEW

**Comment by romoore** [comment]
Merge after #6602

**Comment by jverkoey** [comment]
There are quite a few line changes in this PR; is it possible to split the PR into layout improvements and the new api as two separate PRs?

**Comment by romoore** [comment]
@jverkoey Can you suggest how to split it up? The new API doesn't make sense without the new layout code. The new layout code may introduce truncation that wasn't there previously and so the API was introduced.

**Review by randallli — APPROVED** [review]
@romoore walked me through the changes.

**Pull request merged**
