### PR TITLE
[Shapes] Move shapes from components/private to components/

### PR DESCRIPTION
**Pull request by yarneo**
This is the first part of the migration of moving the Shape libraries away from the private/ folder.

Tracking bug, progress and more details can be found here: #6494 

"Because Shapes and ShapeLibrary have been used in production and are an integral part of the shape scheme and theming. Moreover, with to stop the confusion of clients that the library should not be imported as it is under private, we want to migrate the Shape libs to be under components/ instead of components/private.

The migration will be a 7 step migration to not break clients internally.

1. move the folders to the new directory.
2. Make the old component's BUILD and Podspec targets depend on the new component (and nothing else).
3. Delete all implementation files from the old component.
4. Replace the contents of the old component's headers with import statements to the new component's header. If the new component has headers that match the old component's, then the new component's headers will need to be named uniquely for a period of time to allow clients to migrate over.
5. Once all clients have migrated from the old component, delete the old component. This is a breaking change.
6. If you had to create temporary header names in the new component, then in a separate release add the new headers that you want the new component to use. Move the content of the old headers into the new headers and replace the old headers with an import of the new headers. Migrate clients to the desired headers.
7. Once all clients have moved off of the old headers, delete the old headers.

Passes bazel build and pod build locally.

### CODE REVIEW

**Comment by jverkoey** [comment]
```
Error:
/Volumes/BuildData/tmpfs/src/github/repo/components/private/ShapeLibrary/README.md and 
/Volumes/BuildData/tmpfs/src/github/repo/components/ShapeLibrary/README.md both attempting to write to /catalog/shapelibrary/
/Volumes/BuildData/tmpfs/src/github/repo/docsite-generator/scripts/lib/reporter.js:36
      throw e;
```

**Comment by yarneo** [comment]
Error has been resolved.

**Comment by jverkoey** [comment]
Was this change made as a series of git cp or mv operations? It doesn't look like history is being maintained.

Relatedly: in order to make movement like this a minimally-breaking change the following steps can be taken:

1. git cp the folder to the new directory.
2. Make the old component's BUILD and Podspec targets depend on the new component (and nothing else).
3. Delete all implementation files from the old component.
4. Replace the contents of the old component's headers with import statements to the new component's header. If the new component has headers that match the old component's, then the new component's headers will need to be named uniquely for a period of time to allow clients to migrate over.
5. Once all clients have migrated from the old component, delete the old component. This is a breaking change.
6. If you had to create temporary header names in the new component, then in a separate release add the new headers that you want the new component to use. Move the content of the old headers into the new headers and replace the old headers with an import of the new headers. Migrate clients to the desired headers.
7. Once all clients have moved off of the old headers, delete the old headers.

**Review by jverkoey — CHANGES_REQUESTED** [review]
Requesting changes due to questions regarding the migration process.

**Comment by yarneo** [comment]
@jverkoey let me know if my changes are what you were anticipating for your migration steps. I believe here the .m files history will be kept as I am only moving the files to a different directory. In the next step after we land this release and migrate the internal clients over, we can then do a move to the header files still in components/private to components/ and have the FooNew.h header files point to those instead. Then we land that release and have all the clients now point to Foo.h in the components/Shape and components/ShapeLibrary folders. Then we can delete all the FooNew.h headers

**Review by jverkoey — APPROVED** [review]

**Pull request merged**
