### PR TITLE
[Pesto] Remove extra reusable cell registration

### PR DESCRIPTION
**Pull request by vshijing**
MDCCollectionViewTextCell was registered twice. removed so it only have one.

### CODE REVIEW

**Comment by ianegordon** [comment]
Hi @vshijing.  Please sign the CLA and we'll take a look.  Many Thanks!

**Comment by vshijing** [comment]
I signed it! Thanks

**Review by ianegordon — APPROVED** [review]
Thanks for catching the duplication.

**Comment by vshijing** [comment]
Thanks for review, ianegordon.

**Pull request merged**
