### PR TITLE
[Buttons, TextFields] fix typo in header doc

### PR DESCRIPTION
**Pull request by ralph-e-boy**
fix typo UIConnectSizeCategoryAdjusting -> UIContentSizeCategoryAdjusting

### CODE REVIEW

**Comment by ralph-e-boy** [comment]
I signed the CLA

**Comment by AdibContractorCC** [comment]
@rami-a please provide full regression testing report

**Review by rami-a — APPROVED** [review]

**Comment by ianegordon** [comment]
Thank you @AdibContractorCC !

**Comment by ralph-e-boy** [comment]
thanks @rami-a

**Pull request merged**
