### PR TITLE
[Collections] Updates MDCCollectionViewEditor panning to use cell's center property instead of transform to update its position

### LINKED ISSUE #5328: [Collections] MDCCollectionViewEditor drag and drop uses offset to determine the location of the snapshot cell
The MDCCollectionViewEditor's drag and drop functionality uses offset calculation to determine the moving cell's position. The desire is for the cell to follow the user's touch location. However, this does not work when the collection view is updated, for example when the sections of the collection view are collapsed. The offset is always the same since the reference point (i.e. _initialCellLocation) is only calculated when drag and drop is initiated.

If you are a Googler, see b/117288780 for a reproduction of this behavior.

## Reproduction steps

In a collection view with multiple sections with more than 1 item each, initiate reordering and have the sections collapse to one item each. The change in the cell's original position is not reflected in the offset calculation and therefore the cell does not follow the user's touch correctly.

## Expected behavior

The moving cell's position should always follow the user's touch, even if the collection view is updated once the drag and drop of the cell is initiated.

## Actual behavior

The MDCCollectionViewEditor uses offset calculation to determine the cell's position, and this offset calculation is incorrect when the cell's original position is changed. This results in the moving cell not falling under the user's touch location.

## Platform (please complete the following information)

All devices.

---
#### Internal data
- Associated internal bug: [b/117292550](http://b/117292550)

### PR DESCRIPTION
**Pull request by felixaemiliano**
Note that this solution (using the cell's center property to update its position) is recommended by Apple documentation:
"Use this property to scale or rotate the view's frame rectangle within its superview's coordinate system. (To change the position of the view, modify the center property instead.)"
https://developer.apple.com/documentation/uikit/uiview/1622459-transform?language=objc

The bug is fixed when the cell's position is updated using the center property instead of using an offset in addition to the transform property.

Closes #5328

### CODE REVIEW

**Comment by andrewoverton** [comment]
@felixaemiliano Thank you for the PR! Would you mind resolving the conflicts, and possibly providing a screenshot or gif or something? Thanks!

**Comment by felixaemiliano** [comment]
@andrewoverton Sure, I've resolved the conflicts.

b/117288780 (the bug referenced in the issue #5328 which this PR fixes) contains the before and after videos. PTAL and let me know if there is anything else I can provide.

**Comment by andrewoverton** [comment]
@felixaemiliano "PTAL"! That's a new one for me haha. This all looks great. Thanks again.

**Review by andrewoverton — APPROVED** [review]
~It looks like my last comment was quite right, we should run `git clang-format $(git merge-base origin/develop HEAD)` to appease clang format~

_EDIT:_ It looks like my last comment was **NOT** quite right, we should run `git clang-format $(git merge-base origin/develop HEAD)` to appease clang format

**Comment by andrewoverton** [comment]
I edited my approval comment, there was a typo...

**Comment by jverkoey** [comment]
Is this PR ready to be merged? It looks like it's only blocked on clang-format.

**Pull request merged**
