### PR TITLE
[Dialogs] Remove use of MDCFlatButton for MDCButton and MDCTextButtonThemer

### LINKED ISSUE #3914: [Dialogs] Replace MDCFlatButton usage with MDCTextButtonThemer
Definition of done:

- Any reference to MDCFlatButton has been replaced with MDCButton and MDCTextButtonThemer.
- There are no references to MDCFlatButton in the Dialogs component.

Notable references:

- MDCAlertControllerView+Private.h/m

---
#### Internal data
- Associated internal bug: [b/117178833](http://b/117178833)

### PR DESCRIPTION
**Pull request by codeman7**
Remove all instances of MDCFlatButton within [Dialogs] component
Replace with MDCTextButtonThemer and MDCButton

MDCFlatButton is the old API and MDCTextButtonThemer/MDCButton are the modern APIs.

Closes #3914

### CODE REVIEW

**Comment by ianegordon** [comment]
Would you post a before and after screenshot of one of the complex examples?

**Review by ianegordon — APPROVED** [review]
LGTM.  If there are rendering changes. please note that.

**Review by jverkoey — APPROVED** [review]

**Comment by codeman7** [comment]
I changed the CLA to yes because I am the only author of these commits.

**Comment by codeman7** [comment]
Forgot to post the screenshots.

Before 1 
screen shot 2018-08-09 at 11 36 49 am

After 1
  | screen shot 2018-08-09 at 11 38 57 am


Before 2
screen shot 2018-08-09 at 11 36 15 am

After 2
screen shot 2018-08-09 at 11 39 30 am

**Comment by jverkoey** [comment]
We had to roll this back due to [b/113259339](http://b/113259339).

**Pull request merged**
