### PR TITLE
Update CODEOWNERS to reflect awareness

### PR DESCRIPTION
**Pull request by jverkoey**

### CODE REVIEW

**Review by codeman7 — APPROVED** [review]

**Review by rami-a — APPROVED** [review]

**Comment by romoore** [comment]
I think I'd personally take less of an interest in learning the specific components I had chosen earlier for ownership if I knew that 3-5 other people were also code owners for the same thing.

**Review by fluxminds — APPROVED** [review]

**Comment by yarneo** [comment]
is there a meaning to the ordering of the names within a component, if not can we make it alphabetical so it doesn't make it seem that way?

also, airing Rob's thoughts, I wonder if it's worth putting a limit on the number of owners for a component. If there are more than 2 owners it will make owners more prone to act in a "the other owners will deal with it" mentality.

**Comment by romoore** [comment]
Also, I prefer to have the aspirational, "I want to learn this component and care about its future" of codeowners versus the "here's a list of people who feel like they know how a component works. The distribution of the latter is heavily weighted toward super-simple components (like ShadowElevations).

**Comment by jverkoey** [comment]
Good thoughts gang! Thanks - it looks like we may need to think a bit more about how the team's expertise + review responsibilities should interplay. I'll close this for now until we discuss further.

**Pull request closed without merging**
