### PR TITLE
[Catalog] Made tile creation Xcode 8.2 compatible.

### PR DESCRIPTION
**Pull request by randallli**
catalog/MDCCatalog/MDCCatalogTileView.swift:82:44: error: cannot convert value of type '(CGRect, (NSObjectProtocol & MDCColorScheme)!) -> Void' to expected argument type 'MDCDrawFunc!'
      newImage = MDCDrawImage(defaultSize, MDCCatalogDrawActivityIndicatorTile, colorScheme)
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### CODE REVIEW

**Comment by jverkoey** [comment]
Include the warning in the commit description + code please!

**Review by jverkoey — APPROVED** [review]

**Comment by willlarche** [comment]
Why do we need 8.2 support?

**Comment by randallli** [comment]
@willlarche Its weird for the catalog to require 9.0 and the components require 8.2

**Comment by willlarche** [comment]
Right now our docs say 8.3.3
https://github.com/material-components/material-components-ios/tree/develop/howto/build-env

**Comment by randallli** [comment]
just saw at that myself...
let me check with that. to confirm i need these changes...

**Comment by randallli** [comment]
appears to work for xcode 8.3.3. Im going to drop this PR. Thanks for keeping me honest @willlarche

**Pull request closed without merging**
