### PR TITLE
[Catalog] Verify all examples provide CatalogByConvention methods

### LINKED ISSUE #1897: [Catalog] All example view controllers should implement Catalog By Convention
Some of our examples do not implement:
catalogBreadcrumbs, catalogShouldHideNavigation, etc.

Every example should implement these methods.

### Required
```objectivec
+ (nonnull NSArray<NSString *> *)catalogBreadcrumbs;
+ (BOOL)catalogIsPrimaryDemo;
```

### Optional
```objectivec
- (nonnull NSString *)catalogStoryboardName;
- (nonnull NSString *)catalogDescription;
```

## Informal Protocol (MDCNodeListViewController)
```objectivec
- (BOOL)catalogShouldHideNavigation;
```

### PR DESCRIPTION
**Pull request by romoore**
CatalogByConvention classes require two methods to be implemented:

```objectivec
+ (nonnull NSArray<NSString *> *)catalogBreadcrumbs;
+ (BOOL)catalogIsPrimaryDemo;
```

Closes #1897

### CODE REVIEW

**Comment by ianegordon** [comment]
This is likely a question for @jverkoey as well, but does it make sense to make isPrimaryDemo optional?  Right now it default to 'NO', and that *seems* to be working as intended.

**Comment by romoore** [comment]
I think the biggest challenge with our current approach is that it's hard to understand how to do it correctly.  Correct behavior is defined by a protocol that no class should declare implementing, it works if you do it wrong, and some of the behavior is undocumented.  My suggestion is to make the protocol more formal, and fail if you forget something required.  This makes it easier for contributors to learn how to do it correctly and avoid mistakes.

**Comment by romoore** [comment]
I found a situation where NO example was declared primary and another where two examples were declared primary.  In both cases, the runtime just picked one arbitrarily and went with that.

**Review by jverkoey — APPROVED** [review]
This looks like a good iteration.

In a separate change it may be worth considering alternative ways to construct the catalog's metadata that resolve some of these implicit patterns that aren't necessarily obvious to a newcomer.

**Pull request merged**
