### PR TITLE
[Buttons] Fix issue with legacy dynamic type

### PR DESCRIPTION
**Pull request by codeman7**
## Motivation
The possible code paths for the legacy dynamic type when there are no scaling curves associated with a font are as follows

#### Case 1
```swift
button.mdc_adjustsFontForContentSizeCategory = true
button.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = true
// This should update the font use the legacy *magic* font
```
#### Case 2
```swift
button.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = true
button.mdc_adjustsFontForContentSizeCategory = true
// This should update the font use the legacy *magic* font
```
#### Case 3
```swift
button.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = false
button.mdc_adjustsFontForContentSizeCategory = true
// This should *not* update the font use the legacy *magic* font
```
#### Case 4
```swift
button.mdc_adjustsFontForContentSizeCategory = true
button.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = false
// This should *not* update the font use the legacy *magic* font
```

Currently we only cover cases 1-3, but it's reasonable for a client to get into _Case 4_, this requires a setter for `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` to _undo_ **magic** behavior if the **magic** behavior has been applied.

## Detailed changes
This change adds a setter to `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` to update the fonts accordingly and _undo_ any changes done to the component.

Related to #7464

### CODE REVIEW

**Review by fluxminds — DISMISSED** [review]

**Comment by jverkoey** [comment]
If `mdc_adjustsFontForContentSizeCategory` is enabled and then `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` is disabled, the fonts will have already been adjusted for Dynamic Type using the legacy behavior, so your PR description's statement of "If a client sets mdc_adjustsFontForContentSizeCategory to YES then setsadjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable to NO the fonts should not update." is incorrect if it's implying order. 

Are you expecting that those two things happening in that order should have that expected outcome?

**Comment by jverkoey** [comment]
Speaking offline, Cody brought up the following snippet:

```objc
button.font = <#non-scalable font#>;
button.mdc_adjustsFontForContentSizeCategory = YES;

// At this point, legacy behavior has adjusted the fonts
expectNotEqual(button.font, <#non-scalable font#>;)

button.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = NO;

// At this point, the fonts are still incorrectly adjusted.
expectNotEqual(button.font, <#non-scalable font#>;)
```

If instead, a client did this:

```objc
button.font = <#non-scalable font#>;
button.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = NO;
button.mdc_adjustsFontForContentSizeCategory = YES;
// At this point, the fonts will not have been adjusted.
expectEqual(button.font, <#non-scalable font#>;)
```

After this change, the behavior will instead look like this:

```objc
button.font = <#non-scalable font#>;
button.mdc_adjustsFontForContentSizeCategory = YES;

// At this point, legacy behavior has adjusted the fonts
expectNotEqual(button.font, <#non-scalable font#>;)

button.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = NO;

// At this point, the fonts will have reverted to <#non-scalable font#>
expectEqual(button.font, <#non-scalable font#>;)
```

**Comment by codeman7** [comment]
There should be test for
```swift
button.mdc_adjustFontForContentSizeCategory = true
```

```swift
button.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = false
button.mdc_adjustFontForContentSizeCategory = true
```

```swift
button.mdc_adjustFontForContentSizeCategory = true
button.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = false
```

**Review by jverkoey — APPROVED** [review]
Awesome!

**Comment by fluxminds** [comment]
For:
```
button.font = <#non-scalable font#>;
button.mdc_adjustsFontForContentSizeCategory = YES;

// At this point, legacy behavior has adjusted the fonts
expectNotEqual(button.font, <#non-scalable font#>;)

button.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = NO;

// At this point, the fonts will have reverted to <#non-scalable font#>
expectEqual(button.font, <#non-scalable font#>;)
```

Why should the button font revert back to <#non-scalable font#>? If the font has been adjusted, I would imagine the font shouldn't revert back even if mdc_adjustsFontForContentSizeCategory = NO or adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = NO ?

**Comment by fluxminds** [comment]
In other word, in "Case 4", should the font stay the same? I don't feel it should be the case. For button it might be feasible because it stores a default font, but for some other components, it only stores font in label.font, which is permanently changed by calling `mdc_adjustsFontForContentSizeCategory`.

**Comment by fluxminds** [comment]
@codeman7 @jverkoey since you had a discussion on it.

**Comment by jverkoey** [comment]
If `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` is disabled, the client may reasonably expect that that legacy behavior will no longer be taking effect on the component, thus the intent here to revert to the "expected" results when adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable is disabled.

**Comment by codeman7** [comment]
@wenyuzhang666 in those instances it we should be setting the `ivar` not the `label.font`.

**Comment by fluxminds** [comment]
When `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` is disabled, I would expect the code doesn't adjust the font (which is already scaled by calling mdc_adjustFontForContentSizeCategory before), not the original one. And there is no ivar for many components we have, for example, Banner, List don't have that. I don't think UIKit has this behavior too.

**Comment by fluxminds** [comment]
In other word, I don't think List would be able to implement it, so it would cause deviation for different components. It might be an issue just for Button though.

**Comment by jverkoey** [comment]
I think the distinction comes down to answering this question: should changing this fallback flag result in an immediate side effect update of the fonts?

My assumption was yes, but I could be swayed that the answer should be no, and that this flag should be documented as solely a behavioral modifier for its suffix-sharing counterpart.

@codeman7 what do you think?

**Comment by codeman7** [comment]
The issue is that by setting `mdc_adjustFontForContentSizeCategory` we change the font from your _custom font_ to _material font_ but a client may want to still use their _custom font_. Take a list for example with this snippet.
```swift
let list = MDCStereoListCell()
list.mdc_adjustFontForContentSizeCategory = true
list.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = false
list.titleFont = // A font
list.detailFont = // A font with scaling curves
```
This would result in:
```swift
list.titleFont // Scaling with the legacy curves
list.detailFont // Scaling with the new curves
```
**_Note_** This would work
```swift
let list = MDCStereoListCell()
list.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = false
list.mdc_adjustFontForContentSizeCategory = true
list.titleFont = // A font
list.detailFont = // A font with scaling curves
```
This would result in:
```swift
list.titleFont // Not scaled
list.detailFont // Scaling with the new curves
```


Even though the client asked to ignore the legacy curves. The only error on the client part is the set one flag before setting the other. My general feeling it I shouldn't have to do x then y to get outcome. I should be able to set x and y in whatever order and get the same outcome. If not then that is a bug. 

What do you think?

**Comment by jverkoey** [comment]
+1 to Cody’s example as an argument for this method having side effect behaviors to reduce surprise for clients.

**Comment by fluxminds** [comment]
I agree that the order matters to result doesn't look good. 
However,  the result of 
```
let list = MDCStereoListCell()
list.mdc_adjustFontForContentSizeCategory = true
list.adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable = false
list.titleFont = // A font
list.detailFont = // A font with scaling curves
```
is caused by the default value of `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` is YES, and calling `mdc_adjustFontForContentSizeCategory` depends on it. Even there is a way in Button we could pretend to restore the old value, for List it would need a refactor on itself to implement it. 

Since this flag is expected to be deprecated soon, it may be okay to leave it. I think it is originally a bug on Button that its `fontForState` doesn't get modified when sizeCategory changes.

**Comment by codeman7** [comment]
I'll write up a document today or tomorrow and we'll discuss. I can see an argument for both and I don't want this context to get trapped in comments on a random PR.

**Comment by fluxminds** [comment]
Thanks Cody! It could be really short one. If the bug I mentioned for Button is valid (might be not), then I think it is also hard for Button to implement this logic (restoring old value).

**Comment by jverkoey** [comment]
At minimum we will likely want to document that the ordering of modifications for these two properties matters.

**Pull request merged**
