### PR TITLE
[BottomAppBar] Add basic snapshot tests.

### PR DESCRIPTION
**Pull request by romoore**
Adding a few simple snapshot tests to capture the default appearance of
the bar.

### CODE REVIEW

**Review by jverkoey — APPROVED** [review]
Are the two leading/trailing rtl tests showing bugs? If so please file bugs accordingly if they haven't already been filed.

**Comment by romoore** [comment]
@jverkoey Do you mean https://github.com/material-components/material-components-ios/pull/6644 ?

**Comment by jverkoey** [comment]
That looks similar, but this PR is still demonstrating what appears to be the buggy behavior; does develop need to be merged into this PR?

**Comment by romoore** [comment]
It did - I hadn't gotten around to it yet.  I think it's another strong reason that we should prioritize testing merged PRs and not just what's in the branch (https://github.com/material-components/material-components-ios/issues/6280).

**Comment by romoore** [comment]
@jverkoey I hope it looked similar - I took those screenshots from this PR! ;-)

**Pull request merged**
