### PR TITLE
[Checklist] Status spreadsheet link

### PR DESCRIPTION
**Pull request by willlarche**

### CODE REVIEW

**Comment by ianegordon** [comment]
I was unable to visit the link from my external device.

**Review by ianegordon — DISMISSED** [review]
Please changes permissions to allow view-only access from the public.

**Comment by willlarche** [comment]
Should be good now.

**Review by randallli — APPROVED** [review]
what is the transposed tab? is it supposed to be all our components? looks like it is just 3 right now. Do you need to rerun a script?

**Comment by willlarche** [comment]
Transposed is a tab I made for @ianegordon  that shows the same info inverted so you can do filtering in different ways. I'll clear the filter he's left there.

**Pull request merged**
