### PR TITLE
[Dialogs] Fix for MDCAlertController icon centering.

### PR DESCRIPTION
**Pull request by bambaragoogle**
This PR addresses https://github.com/material-components/material-components-ios/issues/9216
Please advise on any testing implications for this PR.

### CODE REVIEW

**Review by galiak11 — COMMENTED** [review]
Sorry - just noticed all this info is in the issue ticket. We're looking into this.
As for testing, if this results in a visual change, then snapshot testing would probably be best.

**Review by galiak11 — COMMENTED** [review]
I am not able to reproduce the issue.  I used the `DialogsAlertCustomizationExampleViewController` example (see: `performCenteredTitleWithIcon`) from the Dragons App - which seems very similar to the steps that are described in the issue. This example produces an image centered correctly:

Simulator Screen Shot - iPhone 7 - 2019-12-16 at 07 11 51

Additionally, I compared this suggested change with images of different sizes - including very large images that exceed `titleFrame` - and I do not see any difference from the existing code. Both calculate the same value for `titleIconPosition`. 

Can you please elaborate why this fix is needed, or provide as example in which the current calculations are incorrect? (using the examples from Catalog or Dragons apps as a starting point for your example would make it easier to reproduce).

**Comment by bambaragoogle** [comment]
I noticed the issue when testing an alert for which I had specified _only_ a title and icon. I don't believe it makes a difference if there are buttons or not, but populating the `message` seems to make it go away.

**Review by galiak11 — APPROVED** [review]
Thanks for the additional info. I was able to reproduce the issue. And thanks for the fix!

**Pull request merged**
