### PR TITLE
[EarlGrey] Fix earl grey release

### PR DESCRIPTION
**Pull request by willlarche**

### CODE REVIEW

**Comment by ianegordon** [comment]
Tested locally.

**Review by ianegordon — CHANGES_REQUESTED** [review]
Please rebase.

**Comment by willlarche** [comment]
@ianegordon , Done. This was supposed to be a hotfix on the release but it ended up not being included. It's not rebased to develop.

@jgunaratne is fixing a small bug.

**Comment by willlarche** [comment]
The bug @jgunaratne was working on has been isolated and isn't from this PR. The PR is failing Travis because of the logs size problem.

**Review by randallli — APPROVED** [review]

**Review by randallli — APPROVED** [review]

**Pull request merged**
