### PR TITLE
[Examples | Catalog] Updates all components to Swift 4.

### PR DESCRIPTION
**Pull request by codeman7**
Convert all swift code to Swift 4.

Doesn't close any issues.

Had trouble refreshing my fork so had to reclone that's why I have another pull request. Also, before this is merged I have a couple issues.

### CODE REVIEW

**Review by willlarche — CHANGES_REQUESTED** [review]
Thank you! I thought we wanted >=3.2 you said. Why 4 now?

**Comment by codeman7** [comment]
Once we switch to 4.0 being default then it goes to 4.0 but while 3.0 is still the default code then you do 3.2. Does that make sense?

**Comment by codeman7** [comment]
When the Swift 4 compiler is working with Swift 3 code, it identifies its language version as 3.2. As a result, you can use conditional compilation blocks like #if swift(>=3.2) to write code that’s compatible with multiple versions of the Swift compiler.

https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Compatibility.html

**Comment by willlarche** [comment]
Will this cause all files to be compiled in Swift 4? Or is that a framework
/ module setting?

**Comment by codeman7** [comment]
This would make it so we switch the Swift language version to 4.0. If we decide to merge this then if someone uses XCode 8, they need to go and set the 'Use Legacy Swift Language Version' to 'No' in build settings or it won't build.

**Comment by willlarche** [comment]
This is great. So what's missing is setting the target for MDCCatalog to actually build with Swift 4.0. BUT, how do we adjust that by xcode?

**Comment by codeman7** [comment]
I don't think you can have it different settings for different versions of XCode. I think you have to manually do it. Maybe, we should just wait until we drop support for XCode 8 to merge this.

**Comment by willlarche** [comment]
No. I think it’s good even it’s just to be read by potential users. Most
users copy and paste.

**Comment by codeman7** [comment]
But, then other devs will have to go and change the Swift version manually if they want to use MDC-iOS for XCode 8.

**Comment by willlarche** [comment]
Sorry, I meant keep target set to Swift 3 but merge in this swift 4 code even tho it won't be run in testing until we drop Xcode 8 support.

**Review by willlarche — APPROVED** [review]

**Comment by codeman7** [comment]
Should I change all the checks for Swift 4.0 to 3.2?

**Comment by willlarche** [comment]
I'm still not understanding why we'd want it to be 3.2 if the code is 4.

**Comment by codeman7** [comment]
Because we would tell Xcode that we are only using Swift 3, so it makes Swift 4 as Swift 3.2. I am pretty sure Swift 3.2 and 4.0 are the same.

**Comment by willlarche** [comment]
And what's the consequence of leaving as 4?

**Comment by codeman7** [comment]
All the Swift 4.0 code will never be executed.

**Review by willlarche — CHANGES_REQUESTED** [review]
Just tested on 8. It will skip the 3.2 line. Great!
Change them to 3.2 and I think we are done!
Thanks for your patience.

**Comment by codeman7** [comment]
@willlarche I think everything should be good now.

**Comment by willlarche** [comment]
Missing quote from outside conversation:

> So when you switch all the checks to Swift 3.2 then all the renamed APIs are not renamed yet. So that takes out the point of having every #if swift(>=3.2) check. So until support for XCode 8 is dropped then there is no point in having the PR because nothing changes.

**Pull request closed without merging**
