### PR TITLE
[NavigationDrawer] Made DrawerHeaderViewController.swift file to conform to MDCBottomDrawerHeader

### PR DESCRIPTION
**Pull request by anuranBarman**
Added conformation to MDCBottomDrawerHeader for DrawerHeaderViewController.swift file in **NavigationDrawer** examples as it was not showing up if code was run.

### CODE REVIEW

**Comment by anuranBarman** [comment]
I signed it!

**Comment by yarneo** [comment]
hi @anuranBarman, thanks for opening the PR! The header view controller doesn't necessarily have to conform to MDCBottomDrawerHeader as its only method, `updateDrawerHeaderTransitionRatio`, is marked optional. Is there a reason why you added the conformance?

**Comment by anuranBarman** [comment]
As I tried the example by copying the exact code the header was not coming
up. I played with the preferredContentHeight it did not work. But as soon
as I made it conform to MDCBottomHeaderView, just conform, did not add the
stub as it's optional the header showed up.

**Comment by yarneo** [comment]
Can I ask how you copied the code? Was the code not compiling for you without this addition? If that's the case I wonder if you have a different set of compiler flags turned on in your project, as we have never seen it have issues prior.

**Comment by anuranBarman** [comment]
code was compiling but there was no error but drawer was not coming out. After making the changes it came.

**Comment by yarneo** [comment]
ok thanks! will merge.

**Review by yarneo — APPROVED** [review]

**Pull request merged**
