### PR TITLE
[AppBar] Update README.md

### PR DESCRIPTION
**Pull request by ianegordon**
Moved to CGRect() function.

### CODE REVIEW

**Comment by codeman7** [comment]
I don't think this should be in the Swift example.

**Comment by jverkoey** [comment]
Ah! Good catch Cody.

**Comment by codeman7** [comment]
It could be `frame.size.width = appBarViewController.parentViewController.view.bounds.width;` which I believe is equivalent to `CGRectGetWidth();`

**Comment by jverkoey** [comment]
Agreed with Cody. We should also have a separate Objective-C example which does make use of CGRectGetWidth. Ian can you adjust this PR accordingly?

**Comment by ianegordon** [comment]
You had me at: "This is Swift"! 😄 

Dropped.

**Pull request closed without merging**
