### PR TITLE
[MaskedTransition] Fix infinite loops in masked transition example

### LINKED ISSUE #7520: [MaskedTransition] MaskedTransition example crash
The masked transition example crashes with the "Bottom Sheet" and "Centered Card" options due to an infinite loop.

---
#### Internal data
- Associated internal bug: [b/134130287](http://b/134130287)

### PR DESCRIPTION
**Pull request by andrewoverton**
I noticed some crashes in the masked transition example while conducting a FAB accessibility audit. 

@romoore was able to reproduce the crash using iPhone 7/iOS 11.2:

1. Open "Masked Transition (Swift)"
2. Select "Centered Card"
3. Activate (tap) the left Floating Action Button.

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000010a0db3ff in objc::DenseMapBase<objc::DenseMap<DisguisedPtr<objc_object>, unsigned long, true, objc::DenseMapInfo<DisguisedPtr<objc_object> > >, DisguisedPtr<objc_object>, unsigned long, objc::DenseMapInfo<DisguisedPtr<objc_object> >, true>::FindAndConstruct(DisguisedPtr<objc_object> const&) ()
#1	0x000000010a0d977a in objc_object::sidetable_retain() ()
#2	0x0000000109375a7e in thunk for @escaping @callee_guaranteed (@guaranteed UIPresentationController) -> (@unowned CGRect) ()
#3	0x0000000108ebec01 in -[MDCMaskedPresentationController frameOfPresentedViewInContainerView] at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/src/private/MDCMaskedPresentationController.m:51
#4	0x00000001093734e8 in closure #2 in MaskedTransitionTypicalUseSwiftExample.viewDidLoad() at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift:69
#5	0x0000000109375a90 in thunk for @escaping @callee_guaranteed (@guaranteed UIPresentationController) -> (@unowned CGRect) ()
#6	0x0000000108ebec01 in -[MDCMaskedPresentationController frameOfPresentedViewInContainerView] at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/src/private/MDCMaskedPresentationController.m:51
#7	0x00000001093734e8 in closure #2 in MaskedTransitionTypicalUseSwiftExample.viewDidLoad() at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift:69
#8	0x0000000109375a90 in thunk for @escaping @callee_guaranteed (@guaranteed UIPresentationController) -> (@unowned CGRect) ()
#9	0x0000000108ebec01 in -[MDCMaskedPresentationController frameOfPresentedViewInContainerView] at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/src/private/MDCMaskedPresentationController.m:51
#10	0x00000001093734e8 in closure #2 in MaskedTransitionTypicalUseSwiftExample.viewDidLoad() at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift:69
#11	0x0000000109375a90 in thunk for @escaping @callee_guaranteed (@guaranteed UIPresentationController) -> (@unowned CGRect) ()
#12	0x0000000108ebec01 in -[MDCMaskedPresentationController frameOfPresentedViewInContainerView] at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/src/private/MDCMaskedPresentationController.m:51
#13	0x00000001093734e8 in closure #2 in MaskedTransitionTypicalUseSwiftExample.viewDidLoad() at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift:69
#14	0x0000000109375a90 in thunk for @escaping @callee_guaranteed (@guaranteed UIPresentationController) -> (@unowned CGRect) ()
#15	0x0000000108ebec01 in -[MDCMaskedPresentationController frameOfPresentedViewInContainerView] at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/src/private/MDCMaskedPresentationController.m:51
#16	0x00000001093734e8 in closure #2 in MaskedTransitionTypicalUseSwiftExample.viewDidLoad() at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift:69
#17	0x0000000109375a90 in thunk for @escaping @callee_guaranteed (@guaranteed UIPresentationController) -> (@unowned CGRect) ()
#18	0x0000000108ebec01 in -[MDCMaskedPresentationController frameOfPresentedViewInContainerView] at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/src/private/MDCMaskedPresentationController.m:51
#19	0x00000001093734e8 in closure #2 in MaskedTransitionTypicalUseSwiftExample.viewDidLoad() at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift:69
#20	0x0000000109375a90 in thunk for @escaping @callee_guaranteed (@guaranteed UIPresentationController) -> (@unowned CGRect) ()
#21	0x0000000108ebec01 in -[MDCMaskedPresentationController frameOfPresentedViewInContainerView] at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/src/private/MDCMaskedPresentationController.m:51
#22	0x00000001093734e8 in closure #2 in MaskedTransitionTypicalUseSwiftExample.viewDidLoad() at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/examples/MaskedTransitionTypicalUse.swift:69
#23	0x0000000109375a90 in thunk for @escaping @callee_guaranteed (@guaranteed UIPresentationController) -> (@unowned CGRect) ()
#24	0x0000000108ebec01 in -[MDCMaskedPresentationController frameOfPresentedViewInContainerView] at /Users/rsmoore/git/material-components-ios/components/MaskedTransition/src/private/MDCMaskedPresentationController.m:51
```

This small PR fixes the crash.

Closes #7520

### CODE REVIEW

**Review by romoore — COMMENTED** [review]
Please add tests (preferred) or testing steps to the commit message.

**Comment by andrewoverton** [comment]
I don't think we have any tests for examples at this point, and I saw you added steps to reproduce in the issue itself, so is that sufficient? Should I copy those steps to the PR description?

**Comment by romoore** [comment]
@andrewoverton Yes, please add the reproduction steps in the commit message here. That will help us to identify the specific code paths addressed (and potentially those not).  The Issue # link may die in the future, so having the relevant details directly in the commit is probably best.

**Comment by romoore** [comment]
It sounds like this was a bug that was easy to introduce - our own example had it and nobody noticed the mistake when it was rewritten (possibly during a refactor). Is there some documentation or validation in MaskedTransition that we can put in place to prevent this scenario in the future?

**Comment by andrewoverton** [comment]
I updated the PR description to include your reproduction steps 👍 

The crash was introduced while addressing https://github.com/material-components/material-components-ios/issues/3984. My instinct wouldn't be to document this crash in MaskedTransition because it seems to have more to do with the example code than MaskedTransition itself. The issue was that the example was creating a block that called a method that called said block. It's an unfortunate mistake, but my instinct is to just fix it and move on. Hmmm maybe we could add a comment to the blocks explaining the early returns I'm adding? 🤔

**Comment by romoore** [comment]
I think documenting the method that called the block is the best way forward. Clients should know that the method is calling the block itself, so the block cannot call the method. 

If we didn't know not to call that method in that block, nobody else will.

**Comment by andrewoverton** [comment]
@romoore , I added a note in the documentation for a public block property through which the client can end up in the infinite loop situation.

**Review by romoore — APPROVED** [review]

**Pull request merged**
