### PR TITLE
[Dialogs] Fix incorrectly stored files in GIT LFS

### PR DESCRIPTION
**Pull request by galiak11**
# Description
Two snapshot images were not correctly stored in Git LFS, resulting in errors when cloning the repository.
## Error
```
Encountered 2 file(s) that should have been pointers, but weren't:
snapshot_test_goldens/goldens_64/MDCAlertControllerActionsTests/testActionsLayoutHorizontallyForCatpitalizedButtonCase_11_2@2x.png
snapshot_test_goldens/goldens_64/MDCAlertControllerActionsTests/testVerticalActionsAreOrderedByEmphasis_11_2@2x.png
```
## Solution
```
git lfs migrate import --no-rewrite <files>
```

### CODE REVIEW

**Comment by jverkoey** [comment]
It looks like the git lfs files are still being incorrectly uploaded here based on the fact that they're not loading. Is this expected?

**Review by fluxminds — APPROVED** [review]

**Comment by galiak11** [comment]
I’ve followed similar PRs addressing this issue. For example - https://github.com/material-components/material-components-ios/pull/8651

**Comment by andrewoverton** [comment]
I ran the same command in https://github.com/material-components/material-components-ios/pull/9862 to fix incorrectly stored snapshots, and I too was concerned when I couldn't preview them after. I ended up just renaming the test and regenerating the snapshots to be on the safe side, but I think it's worth merging this PR as it stands now to see if it actually does address the issue. I think it does.

**Review by jverkoey — APPROVED** [review]
LGTM based on @andrewoverton's context.

**Pull request merged**
