### PR TITLE
[Chips] Move MDCChipField text input to a new line if text is too wide

### LINKED ISSUE #9006: Internal issue: b/144853451
This was filed as an internal issue. If you are a Googler, please visit [b/144853451](http://b/144853451) for more details.

---
#### Internal data
- Associated internal bug: [b/144853451](http://b/144853451)

### PR DESCRIPTION
**Pull request by bryanoltman**
Updates MDCChipField to move the internal text field down to a new line if:

1. The textField is on the same line as chips and becomes too long to fit
1. The textField is on the line below chips but can fit on the line with chips

Fixes #9006

This completes the roll-forward of https://github.com/material-components/material-components-ios/pull/9828

Before:
before 2020-03-03 15_08_50

After:
after 2020-03-03 15_10_39

### CODE REVIEW

**Review by jverkoey — APPROVED** [review]
No affected test?

Also: love the clarity of this code. Thank you! 🙏

**Comment by jverkoey** [comment]
As mentioned in the other thread, I'm somewhat under the UX impression that the chip input text field should always be on a newline to avoid the jumping behavior being coded here, but am not blocking this PR in terms of it being an iterative improvement.

**Comment by bryanoltman** [comment]
@jverkoey This is kind of tough to test – setting the text programmatically (vs. entering it via keyboard) causes a layout pass, which masks the bug in snapshot tests. Is there a good way to simulate keyboard input? If so, I'll write a couple tests and land those before this PR.

**Comment by jverkoey** [comment]
Hmm we don't have any tests that I'm aware of that do text input simulation, so that may be a reasonable thing to file as a follow-up issue.

**Pull request merged**
