### PR TITLE
[Dialog] Fix alert controller, title and message take half screen even they are nil

### PR DESCRIPTION
**Pull request by ruizhao**
#### Don't forget:
- [ ] Identify the component the PR relates to in brackets in the title. ```[Buttons] Updated documentation```
- [ ] Link to GitHub issues it solves. ```closes #1234```
- [ ] Sign the CLA bot. You can do this once the pull request is submitted.

[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.

### CODE REVIEW

**Comment by ruizhao** [comment]
I signed it!

Googler actually.

**Comment by ianegordon** [comment]
Hi @ruizhao thanks for the PR!  Looks like clabot is unhappy 🙁   I will see if we can't get it sorted out tomorrow when the holiday is over.

**Comment by ruizhao** [comment]
@ianegordon thanks Ian, i think that's because i used my personal account to submit the CL, and i made my google email to be the primary one. let me know if you need me to do anything on my end.

**Comment by ruizhao** [comment]
seems making a comment fixed that 👍

**Review by ianegordon — APPROVED** [review]
Added sample to demonstrate new behavior.
Tested with and without Dynamic Type on iPhone 4S Sim @ 8.1

**Comment by ianegordon** [comment]
Travis is down, tested locally.

**Pull request merged**
