### PR TITLE
[schemes/Typography] Rename MaterialTypography+BasicFontScheme.h to MaterialTypographyScheme+BasicFontScheme.h.

### PR DESCRIPTION
**Pull request by jverkoey**
This is a follow-up to https://github.com/material-components/material-components-ios/pull/8425 and part of https://github.com/material-components/material-components-ios/issues/8424

### CODE REVIEW

**Review by bryanoltman — APPROVED** [review]

**Comment by romoore** [comment]
Isn't "MaterialTypographyScheme" the name for the umbrella in `components/schemes/Typography`?

**Comment by romoore** [comment]
@jverkoey Please provide an Issue that necessitates this work. I'm guessing it's part of a larger project?

**Comment by jverkoey** [comment]
Done.

**Comment by jverkoey** [comment]
> Isn't "MaterialTypographyScheme" the name for the umbrella in components/schemes/Typography?

It is; and this new header is in an extension of that component.

**Pull request merged**
