### PR TITLE
[TextFields] Feature branch merge: Clarity, Safety, Docs, Comments, Formatting

### PR DESCRIPTION
**Pull request by willlarche**
All content was approved as individual PRs.

My legacy.

The main difference is that API has been renamed. If anyone was using `MDCTextInputControllerDefault`, they now need to go to `MDCTextInputControllerUnderline` which is the same functionality.

### CODE REVIEW

**Comment by willlarche** [comment]
@jverkoey , this is the PR with much API change (copy and paste mostly.) I'll let you merge it when it's approved.

**Review by ianegordon — APPROVED** [review]

**Comment by willlarche** [comment]
Whomever merges should be sure to delete the branch.

**Comment by randallli** [comment]
Since this is a rename without any visual changes im going to land https://github.com/material-components/material-components-ios/pull/2655 so we can do some internal demos.

**Comment by willlarche** [comment]
Looks like there aren't conflicts after all.

**Pull request merged**
