### PR TITLE
v59.1.0

### PR DESCRIPTION
**Pull request by jverkoey**

### CODE REVIEW

**Comment by jverkoey** [comment]
Ready for review.

**Comment by ianegordon** [comment]
All authors / committers are Googlers.

**Comment by ianegordon** [comment]
Kokoto-CI seems to be failing on the cocoapods test.

**Review by ianegordon — APPROVED** [review]
Content LGTM, but please identify problem with Kokoro-CI/cocoapods before merging.

**Comment by jverkoey** [comment]
The cocoapods failure is being explored in [b/112053950](http://b/112053950). At this point it appears more likely that the failure is in kokoro than on our end.

**Pull request merged**
