### PR TITLE
[NavigationBar] Deprecate useFlexibleTopBottomInsets

### PR DESCRIPTION
**Pull request by AlimoRabbani**
Deprecate useFlexibleTopBottomInsets and change the default behavior to YES.

### CODE REVIEW

**Comment by jverkoey** [comment]
Whoohoo! How confident are we feeling that this won't cause client regressions?

**Review by jverkoey — APPROVED** [review]

**Comment by AlimoRabbani** [comment]
The first time I made the same change it did not break any automated internal tests, but it broke at least one client and that was discovered in QA testing. I have been in touch with that client directly and they have adopted the new behavior (b/77725966).

Just started another internal testing of this in cl/199123337.

**Comment by AlimoRabbani** [comment]
Lets hold off on merging this until I finish internal testing and possibly updating some clients.

**Comment by jverkoey** [comment]
```
    - WARN  | [MaterialComponents/AppBar, MaterialComponents/AppBar+ColorThemer, MaterialComponents/AppBar+TypographyThemer, and more...] xcodebuild:  Volumes/BuildData/tmpfs/src/github/repo/components/NavigationBar/src/MDCNavigationBar.m:347:12: warning: 'useFlexibleTopBottomInsets' is deprecated: Implement proper vertical alignment with the default YES behavior. [-Wdeprecated-declarations]
    - NOTE  | [MaterialComponents/AppBar, MaterialComponents/AppBar+ColorThemer, MaterialComponents/AppBar+TypographyThemer, and more...] xcodebuild:  /Volumes/BuildData/tmpfs/src/github/repo/components/NavigationBar/src/MDCNavigationBar.h:283:5: note: 'useFlexibleTopBottomInsets' has been explicitly marked deprecated here
    - WARN  | [MaterialComponents/AppBar, MaterialComponents/AppBar+ColorThemer, MaterialComponents/AppBar+TypographyThemer, and more...] xcodebuild:  Volumes/BuildData/tmpfs/src/github/repo/components/NavigationBar/src/MDCNavigationBar.m:394:12: warning: 'useFlexibleTopBottomInsets' is deprecated: Implement proper vertical alignment with the default YES behavior. [-Wdeprecated-declarations]
    - WARN  | [MaterialComponents/AppBar, MaterialComponents/AppBar+ColorThemer, MaterialComponents/AppBar+TypographyThemer, and more...] xcodebuild:  Volumes/BuildData/tmpfs/src/github/repo/components/NavigationBar/src/MDCNavigationBar.m:428:12: warning: 'useFlexibleTopBottomInsets' is deprecated: Implement proper vertical alignment with the default YES behavior. [-Wdeprecated-declarations]
    - WARN  | [MaterialComponents/AppBar, MaterialComponents/AppBar+ColorThemer, MaterialComponents/AppBar+TypographyThemer, and more...] xcodebuild:  Volumes/BuildData/tmpfs/src/github/repo/components/NavigationBar/src/MDCNavigationBar.m:551:16: warning: 'useFlexibleTopBottomInsets' is deprecated: Implement proper vertical alignment with the default YES behavior. [-Wdeprecated-declarations]
    - WARN  | [MaterialComponents/AppBar, MaterialComponents/AppBar+ColorThemer, MaterialComponents/AppBar+TypographyThemer, and more...] xcodebuild:  Volumes/BuildData/tmpfs/src/github/repo/components/NavigationBar/src/MDCNavigationBar.m:575:16: warning: 'useFlexibleTopBottomInsets' is deprecated: Implement proper vertical alignment with the default YES behavior. [-Wdeprecated-declarations]
```

**Comment by AlimoRabbani** [comment]
Are these warnings ok until I mainline the deprecated API in an upcoming PR? Otherwise, I'm not sure how I can do this PR without completely removing the NO behavior.

**Comment by jverkoey** [comment]
I believe you may need to add diagnostics to the warning lines:

```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
// Code referencing a deprecated API
#pragma clang diagnostic pop
```

**Comment by jverkoey** [comment]
Checking in on this - how is the internal testing going?

**Comment by AlimoRabbani** [comment]
I fixed the one broken client, and will update this PR to suppress warnings tomorrow morning.

**Review by jverkoey — APPROVED** [review]

**Comment by AlimoRabbani** [comment]
Added compiler directives around useFlexibleTopBottomInsets usage in MDCNavigationBar to suppress warnings. This PR should be unblocked now.

**Comment by yarneo** [comment]
Thanks @AlimoRabbani! Merging the PR.

**Pull request merged**
