### PR TITLE
[Snackbar] Don't dismiss snackbars on background taps

### LINKED ISSUE #4887: [Snackbar] Should not be dismissable when a user taps outside the button
From the internal report:

> Snackbars should not allow dismissal when the non-button area is activated.  MDC-iOS should remove the dismiss gesture recognizer from the Snackbar's non-button area. 

---

This is an internal issue. If you are a Googler, please visit [b/113074384](http://b/113074384) for more details.

---
#### Internal data
- Associated internal bug: [b/113074384](http://b/113074384)

### PR DESCRIPTION
**Pull request by andrewoverton**
Closes #4887

### CODE REVIEW

**Comment by romoore** [comment]
WANT_LGTM=ianegordon

I think Ian had some serious concerns about this. I want to make sure he approves this before we merge.  This is a major deviation from our current behavior and should probably be carefully rolled-out.  At the very least we should add a flag to MDCSnackbarManager to enable this new behavior.

**Review by yarneo — COMMENTED** [review]
Looked into the Snackbars of the other platforms and looks like iOS is the only one to allow dismissal by tap. Implementors should be mindful that they should keep the Snackbar timeout low to not interrupt the user more than needed. with that being said, because we keep our Snackbar persistent in Voiceover and Switch Control, we will need to keep the dismissal tap for those cases otherwise the Snackbar could potentially stay persistent forever.

**Comment by romoore** [comment]
Guidance around Snackbars for VoiceOver and other accessible technologies is to keep them on-screen until the user "performs an Action" if the Snackbar contains an action button. In this context, "Action" means doing a thing that changes the UI. That may be navigating to a new screen, selecting an element, typing text, or activating a button.

This is a complex issue and it would be nice to make sure we understand all of the inputs before making any changes to our current UX.

**Comment by andrewoverton** [comment]
Glad to see everybody has thoughts on this. My first thought when I saw the issue was that it was going to make a lot of people mad haha. Like, it could easily be mistaken for a regression rather than new intended behavior. I like the idea of a flag.

**Comment by andrewoverton** [comment]
Maybe this PR was premature. Should I close it until we decide what we want to do here?

**Comment by ianegordon** [comment]
Sorry for letting this sit without update.  It is currently being discussing internally:
b/113074384

Let's close for now and we can re-open once we have explicit guidance.

Thank you @andrewoverton !

**Pull request closed without merging**
