### PR TITLE
[Tabs] Fix maximum width logic for centered tabs

### PR DESCRIPTION
**Pull request by brianjmoore**
The previous change didn't work well for small centered tabs, which have a large section inset to achieve their centeredness. This change makes the max width just have a small fixed size class-based inset.

### CODE REVIEW

**Comment by ianegordon** [comment]
Is there a sample to demonstrate this issue?
If not, can we add one?

**Review by ianegordon — APPROVED** [review]
Mirrored from internal.

**Review by ianegordon — CHANGES_REQUESTED** [review]
There may be an outstanding issue with a single justified tab item.

**Comment by brianjmoore** [comment]
Closing and going back to the drawing board on this one.

**Pull request closed without merging**
