### PR TITLE
Use framework-style imports.

### PR DESCRIPTION
**Pull request by sdefresne**
MDFInternationalization is built as a framework, so use the style
recommended to import from the framework (#import <...>).

MotionAnimator and MotionInterchange mixed the normal style import
and the framework style import; settle them on the framework style.

### CODE REVIEW

**Comment by sdefresne** [comment]
@jverkoey Please triage?

**Comment by sdefresne** [comment]
@ianegordon Please triage.

**Comment by jverkoey** [comment]
This may require changes to our .kokoro script as well. The .kokoro script needs to transform MDF framework imports into local imports, similar to the motion header processing step.

**Comment by ianegordon** [comment]
Waiting on Travis before merging.

**Review by ianegordon — APPROVED** [review]

**Comment by ianegordon** [comment]
Rebased and resolved.
Local testing works as expected.
Will merge once Travis gives a +1.
Thank you @sdefresne !

**Pull request merged**
