### PR TITLE
[NavigationDrawer] Fix iOS 9 bottom drawer dismissals

### LINKED ISSUE #5153: Internal issue: b/115858556
This is an internal issue. If you are a Googler, please visit [b/115858556](http://b/115858556) for more details.

### PR DESCRIPTION
**Pull request by andrewoverton**
I noticed that while trying to dismiss the bottom drawer on iOS 9 I got the following error message:
```
attempt to dismiss modal view controller whose view does not currently appear.
```
Then I noticed that if I commented out our override of `-presentedView` I _could_ dismiss the bottom drawer, but I couldn't interact with it.

Finally, I noticed that if I added `self.bottomDrawerContainerViewController.view` as a subview of `super.presentedView` instead of `self.containerView`, I could both dismiss and interact with the bottom drawer, as expected.

This seems to be a good fix, but I'm not really sure. I'm kind of afraid to break something here. Going to wait for @yarneo's input since he has the most knowledge of this component.

Closes #5153.

### CODE REVIEW

**Comment by ianegordon** [comment]
The original override of presentedView is likely to have multiple non-obvious effects. :/

Please verify things work as expected during presentation / dismissal, rotation, older devices and on an iPad in split view and add a comment with the (hopefully positive!) results.

**Comment by andrewoverton** [comment]
You were right @ianegordon ! 9a49867 broke the `BottomDrawerNoHeaderExample` example, which bypasses use of a `MDCBottomDrawerViewController` in its presentation. c47e013 adds a check to see if the presentations controller's `presentedViewController` is a `MDCBottomDrawerViewController` and handles presentation differently if it isn't one.

**Comment by ajsecord** [comment]
Can you please report back on the rest of the tests that Ian requested?

**Comment by andrewoverton** [comment]
@ajsecord, I didn't notice anything unusual except for what I described in https://github.com/material-components/material-components-ios/pull/5202#issuecomment-424016629, and that's all been addressed. I _think_ this one is good to go.

**Review by yarneo — APPROVED** [review]
Looks good, thank you Andrew!

**Pull request merged**
