### PR TITLE
Update our codebase to use .f casts over (CGFloat) casts when using CGFloats.

### LINKED ISSUE #8420: Internal style for floating point values uses the .f suffix rather than casting to CGFloat
In order to align with internal style and reduce friction in internal reviews, we will standardize on the `.f` suffix approach as well.

## Acceptance criteria

- All (CGFloat) casts that can be replaced with a `.f` suffix equivalent have been changed.

### PR DESCRIPTION
**Pull request by yarneo**
Regex ran:
```
Find: \(CGFloat\)(\d+)(?:\.)?(\d*)
Replace: \1.\2f
```

Closes https://github.com/material-components/material-components-ios/issues/8420

### CODE REVIEW

**Review by jverkoey — APPROVED** [review]

**Comment by jverkoey** [comment]
Please land this change in a hotfix release though.

**Review by romoore — DISMISSED** [review]
What was the reason for making this change? There was a team-wide discussion previously about the difference between the two approaches and `(CGFloat)` was decided.  What changed since then? 

Please also link to the appropriate Issue for making this change.

**Comment by jverkoey** [comment]
I've filed https://github.com/material-components/material-components-ios/issues/8420 for the context.

**Comment by jverkoey** [comment]
Closing this PR due to inactivity. Please reopen if needed.

**Pull request closed without merging**
