### PR TITLE
Revert "[TextFields] Add MDCBaseTextFieldLayout object with leading/trailing view behavior (#8292)"

### PR DESCRIPTION
**Pull request by romoore**
These files are not tracked in Git LFS and broke when attempting to merge the
release candidate into `develop`.

Part of #6942

This reverts commit 74c2f3f962636d15a5bfdeb7af6f61db20ea7179.

### CODE REVIEW

**Comment by romoore** [comment]
This broke merging during the release.

```
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
Encountered 4 file(s) that should have been pointers, but weren't:
	snapshot_test_goldens/goldens_64/MDCBaseTextFieldTestsSnapshotTests/testTextFieldWithLeadingViewAndTrailingView_11_2@2x.png
	snapshot_test_goldens/goldens_64/MDCBaseTextFieldTestsSnapshotTests/testTextFieldWithLeadingView_11_2@2x.png
	snapshot_test_goldens/goldens_64/MDCBaseTextFieldTestsSnapshotTests/testTextFieldWithText_11_2@2x.png
	snapshot_test_goldens/goldens_64/MDCBaseTextFieldTestsSnapshotTests/testTextFieldWithTrailingView_11_2@2x.png
Cannot rebase: You have unstaged changes.
Please commit or stash them.

```

**Review by fluxminds — APPROVED** [review]

**Comment by andrewoverton** [comment]
Sorry @romoore :(

**Comment by andrewoverton** [comment]
@romoore and @wenyuzhang666, I probably haven't followed all the recent "git lfs" changes as closely I should have. I don't actually know what I did wrong here haha. Will following these steps resolve this situation?

1) create a new branch after this is merged in
2) revert this revert
3) delete all the snapshot images
4) re-run the snapshot tests, thereby recreating the snapshot images
5) issue a new PR

**Comment by romoore** [comment]
I think as long as you generate the files with the `.gitattributes` changes in your branch, they should be added as Git LFS links.  The best bet is (as you suggested) remove any existing files from the branch and recreate them "cleanly".

**Pull request merged**
