### PR TITLE
[TextFields] Placeholder text is hanging when error text is set to nil

### LINKED ISSUE #2298: [TextField] The placeholder text is hanging when error text is set from non-empty string to nil.
### Reproduction steps
 - Detailed steps to reproduce
```
// When settings up text field, let's say in `-loadView:`
[textInputController setPlaceholderText:textField];

// When getting error
// Observed that the placeholder text is small, and hanging at the top of text field (no problem here).
// The placeholder text color is now the error color.
- (void)textFieldDidEndEditing:(UITextField *)textField {
  ...
  if (error) {
    [textInputController setErrorText:@"Invalid" errorAccessibilityValue:@"Invalid"];
  }
  ...
}

// Now, remove all text in textField in user interface and 
// Observe that the placeholder text becomes bigger, but still hanging at the top of text field
// instead of moving back to original position on top of the text field. The color is now the default
// placeholder text color.
- (void)textFieldDidEndEditing:(UITextField *)textField {
  ...
  if (textField.text.length == 0) {
    [textInputController setErrorText:nil errorAccessibilityValue:nil];
  }
  ...
}
```

### Version number
 - 38.0.1

### PR DESCRIPTION
**Pull request by Andyccs**
#### Don't forget:
- [/] Identify the component the PR relates to in brackets in the title.
- [/] Link to GitHub issues it solves. ```closes #2298```
- [x] Sign the CLA bot. You can do this once the pull request is submitted.

[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.

### CODE REVIEW

**Comment by willlarche** [comment]
Thank you for putting in a PR!

I commented on the issue it closes #2298 that I'm unable to replicate right now. Lemme know what else I need to try to get it to happen.

Also, I don't think we need this call to `updatePlaceholder` here because a couple lines later, on line 1422, `updateLayout` is called which calls `updatePlaceholder` itself.

```
- (void)updateLayout {
  if (!_textInput) {
    return;
  }

  [self updatePlaceholder];
  [self updateLeadingUnderlineLabel];
  [self updateTrailingUnderlineLabel];
  [self updateUnderline];
  [self updateBorder];
}
```

**Review by willlarche — CHANGES_REQUESTED** [review]
See questions in comments.

**Comment by Andyccs** [comment]
I will try to make a small view controller to reproduce the problem I faced. I will update this PR when I got the codes.

**Comment by willlarche** [comment]
Hey @Andyccs ! Just wanted to see what the status was. Could we close this PR and open a new one when the issue is posted?

**Comment by willlarche** [comment]
Closing for now. Update that ticket and hopefully we can reopen! Thank you!!

**Pull request closed without merging**
