### PR TITLE
[FlexibleHeader+UIMetrics] Add BUILD file.

### PR DESCRIPTION
**Pull request by jverkoey**

### CODE REVIEW

**Review by chuga — APPROVED** [review]

**Comment by jverkoey** [comment]
It's a race between travis and kokoro: go! 🍿

**Comment by jverkoey** [comment]
kokoro takes the lead!

**Comment by jverkoey** [comment]
And we have a winner! 5 minute turnaround award goes to: kokorooooo!

**Comment by chuga** [comment]
:tears_of_joy:

**Pull request merged**
