### PR TITLE
[CocoaPods] Added warnings to examples.

### PR DESCRIPTION
**Pull request by randallli**
Turn on warnings from lib for example code.

requires: https://github.com/material-components/material-components-ios/pull/2426 and https://github.com/material-components/material-components-ios/pull/2456

### CODE REVIEW

**Comment by randallli** [comment]
author will merge only because there are blocking prs.

**Comment by ianegordon** [comment]
Please merge once blockers are sorted and CI is happy.

**Comment by randallli** [comment]
@ianegordon i think you forgot to push the approve button.

**Review by ianegordon — APPROVED** [review]

**Comment by ianegordon** [comment]
Please merge once Travis and the blockers are happy.

**Comment by randallli** [comment]
waiting on https://github.com/material-components/material-components-ios/pull/2573

**Comment by randallli** [comment]
waiting on https://github.com/material-components/material-components-ios/pull/2602 and https://github.com/material-components/material-components-ios/pull/2603

**Pull request merged**
