### PR TITLE
[Docs] Adding discord channel link to front page.

### PR DESCRIPTION
**Pull request by willlarche**

### CODE REVIEW

**Review by ShepJGoogle — APPROVED** [review]

**Review by samnm — APPROVED** [review]

**Review by jgunaratne — APPROVED** [review]

**Review by randallli — APPROVED** [review]

**Comment by ianegordon** [comment]
super-nit: Is it possible to have this go directly to the channel (as opposed to the invite page) if you have already accepted the invitation once?  If so it might be preferable.

Otherwise, LGTM.

**Comment by ianegordon** [comment]
super-nit: Is it possible to have this go directly to the channel (as opposed to the invite page) if you have already accepted the invitation once?  If so it might be preferable.

Otherwise, LGTM.

**Comment by willlarche** [comment]
Double checking on that. Also, thinking I'll change it to be the admin inviting instead of 'willlarche'. Ugh. that guy!

**Comment by willlarche** [comment]
@ianegordon Haven't figured out how to do that but changed it to come from admin instead of me.

**Comment by willlarche** [comment]
Oh I don't need to do this at all. There's a badge now on the top. That's much better.

**Pull request closed without merging**
