### PR TITLE
[ActivityIndicator] Rewrite tests in ObjC to prevent the failing unit tests on iOS 13.

### LINKED ISSUE #8239: [ActivityIndicator] Unit test fails on iOS 13.
Add `ci_mode=autobot` in `.kokoro` above `bazel $COMMAND $TARGET --xcode_version $xcode_version --ios_minimum_os=9.0` in `run_bazel()` to reproduce.

Error occurs when testing using Bazel.
```
Test Case '-[components_ActivityIndicator_unit_test_swift_sources.ActivityIndicatorColorThemerTests testColorThemerChangesTheBackgroundColor]' started.
Child process terminated with signal 11: Segmentation fault
```

---
#### Internal data
- Associated internal bug: [b/139096168](http://b/139096168)

### PR DESCRIPTION
**Pull request by fluxminds**
Closes https://github.com/material-components/material-components-ios/issues/8239.

There is not a good way to directly fix it since it maybe XCode beta issue.

### CODE REVIEW

**Review by bryanoltman — APPROVED** [review]

**Review by jverkoey — CHANGES_REQUESTED** [review]
Please describe how you tested this fix in the PR description.

I'm also not 100% confident that we should move forward with this; if the implication is that we can't use Swift for unit tests anymore then I'd like to push back and encourage that we identify the root cause of the issue.

**Comment by fluxminds** [comment]
@jverkoey 
This issue is very similar to https://github.com/material-components/material-components-ios/issues/8219. The tests work fine on XCode but failed on Bazel. (It is also a XCode issue because it fails on XCode if the project is generated on XCode 11) I think it is an XCode beta issue which is caused by using generics in array. https://github.com/material-components/material-components-ios/blob/develop/components/ActivityIndicator/src/MDCActivityIndicator.m#L515 is the line that generates the error (count cannot be called on array), and I don't see the problem with the code itself.

If this approach is not appropriate, how do you feel about maybe disabling it for now?

**Comment by jverkoey** [comment]
Is "count cannot be called on array" the error you're seeing? Are you able to set a breakpoint?

**Comment by fluxminds** [comment]
Since it only fails on Bazel, putting breakpoint on XCode doesn't help. And it is a `segmentation fault 11` which is a SIGSEGV, `print` or `NSLog` doesn't show on the log report.

**Comment by fluxminds** [comment]
I tried commenting out lines and `.count` was the selector that trying to access bad memory and led to the segmentation fault.

**Comment by jverkoey** [comment]
What is `cycleColors` at that point? Can you print it out to the console before it crashes?

**Comment by jverkoey** [comment]
Sounds like `cycleColors` is somehow an invalid object?

**Comment by fluxminds** [comment]
It is not able to be printed out to log because the SIGSEGV failure. But we were able to print the string into an external file. We found out that UIColor object was not able to be printed out because [UIColor description] probably crashes by itself.

I just digged into this issue with @romoore a little bit more. It seems it only happens when UIColor object is passed in an NSArray to objective-c method from swift, and then calling CGColor on it would cause the crash.

It looks like a swift-objC issue because it only happens on swift tests across some components. And it not only happen to UIColor, it also happens to some other object in some cases. For example, [this line](https://github.com/material-components/material-components-ios/blob/develop/components/LibraryInfo/tests/unit/LibraryInfoTests.swift#L35) in LibraryInfo is also causing a SIGSEGV failure too.

**Comment by fluxminds** [comment]
@jverkoey Do you feel if it is reasonable to disable these tests and re-enable them when a golden XCode 11 is release?

**Review by jverkoey — APPROVED** [review]
Am sad, but let's get that runner working! For now it may be wiser to keep the test running in Objective-C at minimum.

Aside: Is this something you feel is a general problem? If so I encourage you to file a Feedback (Radar).

**Comment by fluxminds** [comment]
@jverkoey It is a probably a general problem, I am going to create an issue to collect these errors found in an issue for tracking. (some of those might be ambiguous without digging deep) And I will send those clear ones to Feedback. 

I think it is still healthy to run swift tests (since most of them still passes) on iOS13. I will do a combination of rewriting (preferred one since functional things are still tested) and disabling some of those case by case. I will send them individually for reviews and feedbacks:)

**Comment by acecilia** [comment]
Hi @wenyuzhang666 and @jverkoey 👋 Could you talk a bit about the root cause of this issue?

Was this a Bazel bug?
Was this an xcode bug?
Was it something else?

I am currently experiencing this issue sometimes (flaky test), and this ticket is one of the only ones I found mentioning that bazel/xcode could be the root cause.

Thanks!

**Pull request merged**
