### PR TITLE
[EarlGrey] Removing unused file reference.

### LINKED ISSUE #1509: [Testing] MDCEarlGreyTests fail
Open MDCCatalog in Xcode.
Change your target to MDCEarlGreyTests.
Execute Project->Test...

Error:
<unknown>:0: error: no such file or directory: '/Users/iangordon/projects/gh-material-components-ios/catalog/MDCEarlGreyTests/EarlGrey.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

### PR DESCRIPTION
**Pull request by willlarche**
Fixes #1509

### CODE REVIEW

**Review by ajsecord — COMMENTED** [review]
Is the near-empty folder intentional?

**Comment by willlarche** [comment]
Not really. It's legacy from when there was a 'general' test in there. But that's been removed in favor of a specific test (Snackbar.) I'm testing removing it.

**Comment by willlarche** [comment]
This PR seems to make Travis happy. It is possible to run tests on the target. The tests may not be running and fixing that will come in a different PR. Meanwhile, we are unstuck.

**Review by ajsecord — APPROVED** [review]
Removes the blocker, good enough for the moment.

**Pull request merged**
