### PR TITLE
[Dialogs] Layout fix for MDCAlertController

### LINKED ISSUE #9431: [Dialogs] Alert layout is incorrect after `preferredContentSize` changes
This was filed as an internal issue. If you are a Googler, please visit [b/147670284](http://b/147670284) for more details.

---
#### Internal data
- Associated internal bug: [b/147670284](http://b/147670284)

### PR DESCRIPTION
**Pull request by bambaragoogle**
This change will resolve b/146560712

The above bug describes a situation where the MDCAlertController's scroll views are too wide, and the layout doesn't update to correct them. This change will force the MDCAlertControllerView layout when 'preferredContentSizeChanged' changes, because calling 'setNeedsLayout' is sometimes insufficient.

## Testing
Performed basic tests by reviewing all Dialogs/Alerts examples in the Dragons app to ensure no crashes or obvious errors were introduced.

Fixes #9431

### CODE REVIEW

**Review by galiak11 — APPROVED** [review]

**Review by romoore — CHANGES_REQUESTED** [review]
Thanks for the PR!  However, it looks like there are no tests affected for this change.

Please add a test for this bug.  If an automated test is not possible, please include testing steps and Before/After screenshots to demonstrate the effect of this change.

**Comment by jverkoey** [comment]
Work required for us to merge this in:

- [ ] Perform manual review/testing in the catalog to verify this doesn't break Dialogs in any obvious way.
- [ ] Kick off an internal presubmit to verify it doesn't cause any tests to fail.

EDIT(romoore): Clarified the expected testing steps after offline discussion with jverkoey.

**Comment by jverkoey** [comment]
I've kicked off internal testing in [cl/289786897](http://cl/289786897).

**Comment by jverkoey** [comment]
The internal testing has revealed some expected screenshot test changes that will need to be updated as part of the release that contains this PR.

**Review by romoore — APPROVED** [review]
Tested on iPhone 4s/iOS 9.3, iPad 2/iOS 9.3, iPhone XR/iOS 12.4 simulators.  Found no new issues caused by this change.

**Pull request merged**
