### PR TITLE
[Catalog] Make the catalog use a dynamic color scheme

### PR DESCRIPTION
**Pull request by codeman7**
This updates the catalog to use the dynamic color scheme `.material201907`.

| Before | After |
| --- | --- |
|cat-before|cat-material|

### CODE REVIEW

**Review by yarneo — COMMENTED** [review]
For the primary primaryvariant and secondary, did you just inverse the colors?
Do you recall where we got the original colors from, and if we should just directly map to our color scheme instead of overriding?

**Comment by codeman7** [comment]
I don't know where the original colors come from, if we use our scheme out of the box then it would be light/dark purple. I think for MDCDragons we can use our scheme out of the box. For the catalog I think this should be okay until design gives us the correct colors.

**Comment by yarneo** [comment]
I propose we use our defaults throughout the catalog app, as the catalog app is supposed to showcase Material and Dragons should be un-themed to allow us to debug without noise.

**Comment by codeman7** [comment]
I'm good with that, I've updated the PR.

**Review by yarneo — APPROVED** [review]

**Comment by codeman7** [comment]
This bring us into alignment with the Android team.

**Pull request merged**
