### PR TITLE
[BottomNavigation] Fix shadow elevation value

### PR DESCRIPTION
**Pull request by romoore**
The Bottom Navigation should have an elevation of 8 dps instead of 6 based on
the latest design guidance.

**Before**
bottomnav-ex-original

**After**
bottomnav-ex-after

### CODE REVIEW

**Comment by romoore** [comment]
Since this is based off of #4194 , marking as WIP but it should be reviewed.

**Comment by romoore** [comment]
@material-prbot That's from a diffbase, once the parent commit is merged this is a single-component change.

**Comment by romoore** [comment]
The fact that Bottom Navigation Bar has *never* cast a shadow is tracked in #4193

**Review by ianegordon — APPROVED** [review]
LGTM once the previous PR has landed.

**Pull request merged**
