### PR TITLE
Add demonstration of Shadow Issues

### PR DESCRIPTION
**Pull request by ianegordon**
This demo reproduces the issues in #1287.

### CODE REVIEW

**Review by willlarche — CHANGES_REQUESTED** [review]
Needs licensing stanzas.

**Comment by ianegordon** [comment]
Licenses added.
README.md (from Pesto) added.
PTAL.

**Review by willlarche — APPROVED** [review]

**Comment by willlarche** [comment]
Looks like Travis is unhappy with ZShadow.

**Comment by ianegordon** [comment]
Travis-CI:
Failed to build ZShadow in /Users/travis/build/material-components/material-components-ios/scripts/../demos/ZShadow/ZShadow.xcworkspace:
xcodebuild: error: The workspace named "ZShadow" does not contain a scheme named "ZShadow". The "-list" option can be used to find the names of the schemes in the workspace.

Local:
xcodebuild -list -workspace ZShadow.xcworkspace
Information about workspace "ZShadow":
    Schemes:
        ZShadow
        MaterialComponents
        Pods-ZShadow

*sigh*
(Still looking)

**Comment by ianegordon** [comment]
To close the loop, the resolution was to make the ZShadow scheme Shared.

**Pull request merged**
