### PR TITLE
[Snackbar] Message View Styling.

### PR DESCRIPTION
**Pull request by seanoshea**
A replacement for https://github.com/material-components/material-components-ios/pull/670.

### CODE REVIEW

**Comment by seanoshea** [comment]
With https://github.com/seanoshea/BostonFreedomTrail/pull/190/commits/7185af9b160f6cbf7a875e03304dfdb50a9fb151, https://github.com/seanoshea/BostonFreedomTrail/pull/190 and https://github.com/material-components/material-components-ios/pull/1120/commits/bd88915bbda26e4494d5634ca06a695f805e6921, I seemed to be able to style the snack bar message background color and text color.

cc @ianegordon @ajsecord

**Comment by seanoshea** [comment]
Did a little investigation into how other view-based libraries manage this and found:
```
https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionView.m#L17
https://github.com/Instagram/IGListKit/issues/294
https://github.com/jessesquires/BButton/blob/develop/BButton/Classes/BButton.m#L188-L201
```
I like the idea of overriding the getter and defaulting to the `appearance` setting in https://github.com/jessesquires/BButton/blob/develop/BButton/Classes/BButton.m#L193.

What do you think?

**Comment by ianegordon** [comment]
I think there is a workaround where we don't have to check against nil.  (Your concern above)

I've pulled out my demo code to try and lock down the magic order / combination.

[C&P some old notes on UIAppearance]

Initial Thinking:

Default values for properties annotated with UI_APPEARANCE_SELECTOR must be set in +initialize on the UIAppearance proxy..

Default values for properties annotated with IBInspectable should be set on the _ivar in -commonClassInit.  If you have explicitly set a value to the property in your Storyboard, it will get set by the OS after this method.

Default values for properties that are neither UI_APPEARANCE_SELECTOR nor IBInspectable should be set in -commonClassInit on the _ivar if they are non-zero.

UIView subclasses should be annotated IBDesignable.

UIView subclasses should have a -commonClassnameInit method that is called from both -initWithFrame and -initWithCoder.

**Comment by seanoshea** [comment]
OK - I think all those `nil` checks were unnecessary.

Unsure of whether it makes sense to make these new properties `IBDesignable` per your notes above, but willing to be convinced otherwise.

I guess one other thing we could do in this PR would be to override `initWithCoder:` and `initWithFrame:` and use a `commonSnackbarMessageViewInit` method?

**Comment by ajsecord** [comment]
@seanoshea, @ianegordon don't worry about the Travis CI—I'll fix it later.

**Comment by seanoshea** [comment]
@ajsecord - ok. Didn't realize that the travis-ci boxes came pre-packaged with `swiftlint`. There must be a way to only try a `brew install` if the min version of `swiftlint` is not already installed on the machine.

Will fix my unit tests and revert that small change to the travis script.

**Comment by ajsecord** [comment]
Yeah...it also looks like different versions of brew consider the "already installed" case to be error vs warning. Sorry for the confusion!

**Comment by seanoshea** [comment]
Frustrated by the inability to fully unit test this out, but as there's no host window to add the `MDCSnackbarMessageView` to, the `UIAppearance` additions are never triggered in a unit test environment.

I'm not exactly psyched about not having the PR have any unit tests associated with it - open to suggestions if you have any for testing out this kind of functionality.

**Pull request merged**
