### PR TITLE
[TextFields] Add identity check in -setTextColor: in MDCTextField

### LINKED ISSUE #9470: [TextFields] Infinite loop in `layoutSubviews` on iOS 13
This was filed as an internal issue. If you are a Googler, please visit [b/148159587](http://b/148159587) for more details.

---
#### Internal data
- Associated internal bug: [b/148159587](http://b/148159587)

### PR DESCRIPTION
**Pull request by andrewoverton**
This PR adds an identity check in `-setTextColor:` in MDCTextField. This identity check short circuits an infinite loop triggered by `-setTextColor:` under certain mysterious circumstances involving the MDCTextField layout pass and MDCFlexibleHeaderView KVO stuff surrounding safeAreaInset changes. I don't fully understand what's going on tbh :)

The internal bug ([b/148159587](http://b/148159587)) has links to before and after gifs in the comments.

Closes #9470

### Update: The internal client who reported the bug was unable to reproduce it with these changes.

### CODE REVIEW

**Comment by bryanoltman** [comment]
How did you verify that this fixes the issue?

**Comment by andrewoverton** [comment]
I built the app and added a bunch of breakpoints and eventually zeroed in on which method calls were necessary to trigger the infinite loop and then found a way to make it so they weren't made again and again and again. It's bizarre. There's some interplay between the layout process of the text field and some "safeAreaInsetsDidChange" logic in flexible header that is just no good!

**Comment by andrewoverton** [comment]
Oh and I updated the PR description to link to the bug which links to some before and after gifs

**Review by bryanoltman — APPROVED** [review]
I'd maybe add a comment above the `textColor != self.textColor` check mentioning why you added it, just in case someone thinks it's an unnecessary optimization somewhere down the line.

**Comment by andrewoverton** [comment]
Good idea, I'll do that

**Pull request merged**
