### PR TITLE
[Palettes] Add shared RGBA -> UIColor utility

### LINKED ISSUE #1221: [Palettes] Replace hex to RGB functions w/ dependency to Palettes and its function
### Overview
Several pods have a hex to RGB function. There's already one in the Palettes tho. Let's migrate to that and make Palettes a common lightweight dependency.

### Reproduction steps

See:
37:MDCPalettes.m:
static inline UIColor *ColorFromRGB(uint32_t rgbValue) 

65:MDCButton.m:
static inline UIColor *MDCColorFromRGB(uint32_t rgbValue)

36:MDCCollectionInfoBarView.m:
static inline UIColor *ColorFromRGB(uint32_t rgbValue) 

30:MDCProgressView.m:
static inline UIColor *MDCColorFromRGB(uint32_t rgbValue) 

33:MDCSlider.m:
static inline UIColor *MDCColorFromRGB(uint32_t rgbValue)

### PR DESCRIPTION
**Pull request by romoore**
Creating a single implementation of uint32_t -> UIColor code. We had several
different (but effectively identical) versions of this same code sprinkled
throughout different components. Although this increases dependency on
Palettes, the size of Palettes is only around 30 KiB.

Closes #1221

### CODE REVIEW

**Review by ajsecord — CHANGES_REQUESTED** [review]
We try to reduce near-trivial deps between components to avoid a tangled dependency graph. For one-liner/inlined simple functions, just copy-and-paste. Your instinct is correct, but now you know why we do this.

**Comment by material-admin** [comment]
Spoke offline with @romoore and I think that a private colorUtility component would not tie it to Palettes.

**Comment by randallli** [comment]
Spoke offline with @romoore and I think that a private colorUtility component would not tie it to Palettes.

**Comment by ajsecord** [comment]
Please don't! This isn't worth a separate component.

**Pull request closed without merging**
