### PR TITLE
Release candidate v41.0.0

### PR DESCRIPTION
**Pull request by jverkoey**

### CODE REVIEW

**Review by ajsecord — CHANGES_REQUESTED** [review]
Lots of breaking changes—why isn't this a major version bump?

**Comment by jverkoey** [comment]
Fixed!

**Review by ajsecord — APPROVED** [review]

**Comment by ianegordon** [comment]
Do we need to rerun bump?
I see the podspec and changelogs don't reflect 42.0.0?

**Review by ianegordon — CHANGES_REQUESTED** [review]
Version stamp isn't consistent.

**Comment by jverkoey** [comment]
Bumped!

**Review by ianegordon — APPROVED** [review]

**Pull request merged**
