### PR TITLE
[Collections] Dynamic height for more than 3 lines.

### PR DESCRIPTION
**Pull request by alexfacciorusso**
Added helper method for calculating height of the cell based on
number of text and detail lines with support for more than
three lines of text.

### CODE REVIEW

**Comment by alexfacciorusso** [comment]
I signed it!

**Comment by ianegordon** [comment]
Hi Alex, thank you for the PR!  I apologize for the slow response, but we are working on collections right now and I want to make sure your changes won't conflict with some of the internal changes that are in progress.  We are looking into the way we do cell sizing, adding support for Dynamic Type and some other refactoring.  Let me discuss with some of the engineers and determine the next steps.

**Comment by ianegordon** [comment]
Hi Alex.  I wanted to touch base so you know we haven't forgotten about this.  We've been landing some Collections refactoring and have more in-flight.  As far as the cells, we are looking at moving to self-sizing cells so we don't have to increase the surface of the API.

**Comment by alexfacciorusso** [comment]
No problem! Thank you for the beautiful library (well librar*ies*, considering the material components for all the different platforms): trying to give back is the minimum I can do 😁

**Comment by ajsecord** [comment]
@ianegordon any update on this? Can we merge Alex's change and deal with changes to Collections later?

**Comment by ianegordon** [comment]
The concerns are:
1. We want to move to self-sizing cells.
1. We need to work well with Dynamic Type.
1. This exposes an additional public class method which we would then deprecate when we handle the concerns above.

@felixaemiliano has been looking at this in the context of an internal project.

**Comment by ajsecord** [comment]
So it sounds like we should close this in preference to some kind of feature request issue for your point #1. Could you point to or create that issue and then close this? We can always reopen when the time is right.

**Comment by ianegordon** [comment]
Thanks for the PR Alex.  

Issue #1634 created.

Closing.

**Pull request closed without merging**
