### PR TITLE
[List Items] List item cell prototypes AGAIN (API Review)

### PR DESCRIPTION
**Pull request by andrewoverton**
In addition to some prototypes, this PR contains `ManualLayoutListBaseCell2` and `ManualLayoutListItemCell2`, which are proposed List Item cell classes. I’m still making tweaks to their APIs and implementations (and the names of the classes will change) but feedback on either is still welcome. Thanks!

_Previously:_

I have done more testing since the last time I spoke face to face with everyone during Thursday morning’s stand up. `ManualLayoutListItemCell2` is the fastest solution, but @yarneo's `CollectionViewListCell` is not significantly slower, and it comes with all the benefits of Auto Layout. Picking an approach to move forward with is a pre-requisite of a design doc actually being written. There should also be consensus on what the API of the preferred solution should look like.

Here is [a spreadsheet](https://docs.google.com/spreadsheets/d/1H_u4ryLn-avtPJBfwVd6krDF5o4aL6AEEK8v0FXtyuo/edit?usp=sharing) with performance testing FPS data from `ManualLayoutListItemCell2`, `AutoLayoutListItemCell2`, and `CollectionVIewListCell`. I did two tests for each. The averages for each test for each device can be seen in the 12th and 24th rows.

Based off A) these performance metrics, and B) the implementations of the various solutions (none of which are complete) which solution does everyone think we should go with?

Thanks for reading and helping move this forward! :)

### CODE REVIEW

**Comment by jverkoey** [comment]
I vote for giving us as much headroom as possible performance-wise and going with the manual layout approach. This will give us the most control over dialing in the performance.

**Comment by jverkoey** [comment]
Expanding on this thinking: we have a lot of utility APIs for handling the layout features we desire here, such as RTL and dynamic type.

Without auto layout, is implementing a self-sizing version of our very focused concrete cell doable?

**Comment by andrewoverton** [comment]
I've been working on the design doc, you can check it out [here](https://docs.google.com/document/d/1Cz4vHKz5lSreV3d0jhXJhyP4RbFeTo2u3Jszi9hBayw/edit?usp=sharing)

**Comment by ianegordon** [comment]
Requested Use Case in #4396

**Comment by ianegordon** [comment]
Requested Use Case in #4395

**Comment by andrewoverton** [comment]
I had a meeting with @ianegordon about what’s up here so far and here’s what we decided should happen next:

- First I should merge this PR. It’s up against an experimental branch that I own, so there’s no harm in doing so.
- Afterward, I’ll open up another PR against the base branch `experimental-lists` with the edits he suggested in our meeting.
- Then I’ll issue a PR against `develop` with just the headers from the second PR’s branch.

**Pull request merged**
