### PR TITLE
[MDCTabBar] Remove dependence on a UIWindow for rendering/layout of MDCTabBa

### LINKED ISSUE #5245: [MDCTabBar] Remove dependence on a UIWindow for rendering/layout of MDCTabBar
## Feature Request/Suggestion

We use snapshot testing to test a lot of our views and spot regressions. I've currently trying to add snapshots for our AppBar but unfortunately I cannot snapshot it when it contains an MDCTabBar (see screenshots, below).

Hunting down the reasons for this I found the following checks in the code:

1. [A soft check for a window in MDCItemBar](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/src/private/MDCItemBar.m#L627)
2. [An assertion for a window in MDCItemBar](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/src/private/MDCItemBar.m#L659)
3. [A soft check in `didMoveToWindow` in MDCItemBarCell](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/src/private/MDCItemBarCell.m#L320)

And the following usages of window that the comments refer to:

4. [A check for a window to decide whether to animate selected changes in MDCItemBarCell](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/src/private/MDCItemBarCell.m#L342)
5. [A query of the window screen scale in layoutSubviews in MDCItemBarCell](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/src/private/MDCItemBarCell.m#L297)
6. [A query of the window screen scale in `updateTransforms` in MDCItemBarCell](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/src/private/MDCItemBarCell.m#L508)

To enable snapshot testing (or any kind of rendering offscreen) it propose changing usages 5 and 6 to use `UIScreen.main.scale` and so remove the requirement for a window. (Usage 4 actually makes sense as a check in the absence of passing an 'animated' bool to `setSelected`). In that case then  removing checks 1, 2 and 3 is possible which will allow the tab bar to be rendered properly.

## Additional context

I have tried but have been unable to find a way to fake a UIWindow for our snapshot tests (they are ran as Unit tests as we are using [iOS Snapshot Test Case](https://github.com/uber/ios-snapshot-test-case/)). Creating a window and using it in a unit test does not seem possible (or am I missing something?)

## Snapshots

Before the above changes, the snapshot looks like this:
testtabbar 2x

Afterwards it looks like:

testtabbar 2x copy

This is due to parts of the layout being skipped in the absence of a window for the `MDCItemBar`

### PR DESCRIPTION
**Pull request by samskiter**
Closes #5245 

Per convention in the rest of the MDC code base - the `UIScreen.mainScreen` is used when a window is not available.

### CODE REVIEW

**Comment by jverkoey** [comment]
I think the linked-to issue may be incorrect - it's pointing to a pull request.

**Comment by samskiter** [comment]
@jverkoey fixed...

**Review by jverkoey — APPROVED** [review]

**Comment by jverkoey** [comment]
Please add a test for this change to the Tabs unit test code so that we can avoid regressing this behavior.

**Comment by samskiter** [comment]
Testing this is difficult without snapshotting infrastructure as the old code failed silently - just rendering wrongly. Added a TODO to add a snapshot test after #5199 is addressed.

**Comment by romoore** [comment]
To be clear, our snapshot tests use a host application and have UIWindows. We do not currently have the ability to perform snapshot testing without a host application.

**Comment by samskiter** [comment]
@romoore see https://github.com/material-components/material-components-ios/issues/5199 for notes on testing without a window and as a unit test (v fast)

**Comment by samskiter** [comment]
@romoore see https://github.com/material-components/material-components-ios/issues/5199 for notes on testing without a window and as a unit test (v fast)

**Pull request merged**
