### PR TITLE
[Documentation] Adds a "getting started" section to contributing/README.md

### PR DESCRIPTION
**Pull request by Ruberik**
Thanks to @codeman7 for his help getting me started on #6151. I found this hard enough to do on my own that I thought others might have trouble too. I realize there are many questions of taste that go into this sort of documentation:
- Does it belong here, or somewhere else?
- Are any of the steps too detailed, or not detailed enough?
- Does it start too early? In other words, would anybody who's reading this actually need the first few steps?
- Should I mention how to work around #5825 as a Known Issue, or should I assume that will get fixed soon enough that it isn't worth mentioning?

I'm assuming I don't have this written *exactly* the way you'd like it, so this PR is intended to start a discussion.

### CODE REVIEW

**Comment by randallli** [comment]
Thanks for the PR that tries to fix our confusing docs. Clearly our docs are missing a couple things because we had to give you more explicit instructions than our existing docs. 

> Does it belong here, or somewhere else?

Some of this is elsewhere already. I would like to use links to our docs where we talk about it as well as GitHub references that explain things too. I will inline my thoughts.
> Are any of the steps too detailed, or not detailed enough?

We may be able to convert some of the details to links to GitHub help docs. (I will inline)
> Does it start too early? In other words, would anybody who's reading this actually need the first few steps?

Some things we can assume the user has already installed. Xcode and git to name a few. I will inline exactly which ones i feel can be omitted.
> Should I mention how to work around #5825 as a Known Issue, or should I assume that will get fixed soon enough that it isn't worth mentioning?

No need to call this out just yet. I believe @andrewoverton put in a fix for. We can confirm its status in the issue.

**Comment by randallli** [comment]
Instead of in lining the comments I tried to do a PR on top of yours but accidentally merged the changes directly into your branch. If your ok with my additions we can merge this in.

**Review by randallli — APPROVED** [review]

**Comment by Ruberik** [comment]
LGTM. That looks way better. Thank you!

**Comment by randallli** [comment]
I reran the kokoro CI.
We need to merge develop so that we get #6184 which should fix the failing kokoro/pr/website check.

**Comment by Ruberik** [comment]
Thanks for taking this over and making it happen, @randallli!

**Pull request merged**
