### PR TITLE
[Ripple] Remove setting frame based on superview

### LINKED ISSUE #7329: Ripple does not allow you to configure where it should be presented within its parent view
The following lines cause the Ripple to always fill its parent container's bounds, which removes the ability for the owner of the Ripple view to determine its layout.

https://github.com/material-components/material-components-ios/blob/4a160e5de63b82f073f7068465ddf5005a7809ff/components/Ripple/src/MDCRippleView.m#L72-L76

Subviews typically should not be relying on any part of the parent view hierarchy to perform layout, instead solely relying on the bounds of self.

Furthermore: layoutSubviews should never set self.frame. This is an anti-pattern.

---
#### Internal data
- Associated internal bug: [b/131839790](http://b/131839790)

### PR DESCRIPTION
**Pull request by codeman7**
In order for [`MDCRipple`](https://github.com/material-components/material-components-ios/tree/develop/components/Ripple/src) to support customizable ripple size the superview needs to be able to adjust the ripple view's frame. By setting the frame to the superview's frame it overrides whatever the superview sets within its `layoutSubviews` method. This removes that override to allow for a more customizable ripple.

Closes #7329

### CODE REVIEW

**Review by yarneo — COMMENTED** [review]
Please make sure the examples using Ripple are still setting up the RippleView correctly to fill the container bounds, and that it works well with orientation changes. 

I assume it should be ok because of the autoresizingMask, but please verify as this could potentially break many clients.

**Comment by codeman7** [comment]
I have tested against Chips, Cards, Buttons and this allows customization of the rippleView's frame but by default sizes the rippleView to the frame of the superview.

**Review by jverkoey — APPROVED** [review]

**Comment by codeman7** [comment]
Waiting on LGTM from @yarneo

**Review by yarneo — APPROVED** [review]
awesome! thanks for adding these tests.

**Pull request merged**
