### PR TITLE
[AppBar] View controllers can override AppBar injection.

### PR DESCRIPTION
**Pull request by romoore**
Even though the AppBarNavigationController can be very useful for clients,
there are some edge cases where a specific view controller being pushed should
*not* have an MDCAppBar injected into its view hierarchy. This may be because
the view controller already has some other header view that functions
similarly to an AppBar or because designs call for that particular view to not
have an AppBar.

### CODE REVIEW

**Comment by jverkoey** [comment]
Thanks Rob! This is definitely an area of challenge with the navigation controller API. Note that the MDCAppBarNavigationController will avoid adding an App Bar if a Flexible Header / App Bar was already present in the pushed view controller's view controller hierarchy.

One consideration to keep in mind is that most users of the navigation controller will be using self.navigationController, which is typed as a UINavigationController.

Can you give an example of how you feel clients should use this API with that consideration in mind?

**Comment by romoore** [comment]
Yep, for an internal client, I had to do the following:

```objc
- (void)putTheViewControllerOnScreen {
  if ([self.navigationController isKindOfClass:[MDCAppBarNavigationController class]]) {
    MDCAppBarNavigationController *navigationController = 
        (MDCAppBarNavigationController *)self.navigationController;
    [navigationController pushViewController:self.theViewController 
                                    animated:YES
                                injectAppBar:NO];
  } else {
    [self.navigationController pushViewController:self.theViewController animated:YES];
  }
}
```


This was because the VC pushing the other didn't know whether or not an app bar was being inserted. Since MDCAppBarNavigationController only checks for specific UIView subtypes (like FlexibleHeader), there wasn't anything the presenting view controller could do.

**Comment by jverkoey** [comment]
In this case is the caller of `push` the one that best knows whether `self.theViewController` should have an app bar injected?

**Comment by romoore** [comment]
No, the VC being pushed knows more, but it cannot know about the AppBar component.  As a result, the first place the knowledge could exist was in the VC doing the pushing.

**Comment by jverkoey** [comment]
For historical context can you link to any cls or bugs that informed this change please?

**Comment by romoore** [comment]
I don't have a CL yet because it's waiting on this functionality to be merged internally.

**Comment by romoore** [comment]
@jverkoey Can you provide  some help here - is there another API I should be using to prevent injection of an AppBar into a specific VC?

**Comment by jverkoey** [comment]
> I don't have a CL yet because it's waiting on this functionality to be merged internally.
 
I understand. It sounds like this change was informed by a need from an internal client in your comment “Yep, for an internal client, I had to do the following:”. Is there any way we can link to that context?

Regarding this change, I’m hesitant to encourage view controllers being aware of the navigation controller and would like to know what other options might be available here.

**Comment by romoore** [comment]
I'm open to any suggestions you have, but I couldn't figure out another way to prevent injection of an AppBar.  The alternative is for the internal client to abandon the AppBarNavigationController.

Here's a change that doesn't actually have support for this change, since this hasn't landed.
cl/221475143

**Comment by romoore** [comment]
@jverkoey To be absolutely clear here, what steps must I take to get to an Approval/LGTM on this PR?

**Comment by jverkoey** [comment]
This is a change in how this API is meant to be used, so I'd like to make sure we've explored alternatives before committing to a solution.

One of the constraints that is important to maintain with MDCAppBarNavigationController is that view controllers pushed onto it have no awareness of the MDCAppBarNavigationController. This allows clients to write view controllers that care as little as possible about the App Bar.

With this in mind, one alternative solution is to move the decision not to inject an App Bar into the MDCAppBarNavigationController delegate logic. For example, there might be a delegate callback that an app can implement that asks whether an App Bar should be injected for a given view controller. In this case, the app would return NO for the view controller they're trying to push.

**Comment by romoore** [comment]
I see. I think it will be easier for me to just write this up as a category in the client rather than providing this behavior in the component. Thanks for clarifying!

**Comment by jverkoey** [comment]
This is not a pattern that I feel we should encourage or support for clients. Using a category is not a fix for the root problem which may reasonably be faced by other clients as well.

Why did you feel the need to delete this PR?

**Comment by romoore** [comment]
I don't see how a single delegate could understand all of the nuances of presenting a VC deep within an application (local knowledge). Since the original proposal (allowing the local presenter to decide) was unfavorable, it's easier to unblock the client code by extending the behavior than to try and solve for all possible solutions.

**Comment by jverkoey** [comment]
Is the delegate of the navigation controller part of the application logic as well? If so, the app is aware of using the MDCAppBarNavigationController and by extension, potential needs for constraints of its use.

**Comment by romoore** [comment]
In this case it is, but I do not know that is the case for all clients and all use cases. As such, I want to unblock the client code quickly and move forward. If you would like to propose a design for a new API on the AppBar or its delegate, it should probably be an Issue rather than a discussion in an abandoned PR attempting something different.

My suggested API was to allow clients to use local decision-making to choose not to inject an AppBar when it did not make sense. If that decision needs to be made global (a single delegate), I think it requires significant consideration and perhaps a few rapid prototypes to see how it might work in practice.

**Comment by jverkoey** [comment]
Can you share more detail on how you’ll extend the app bar navigation controller behavior? This question is related to this PR because as best I can tell, we would need to add new functionality to the app bar navigation controller (as you’ve done in this PR) in order to achieve this local behavior.

Relatedly, it sounds like you’re working on a p0 or p1 based on your tone. Is this the case?

**Pull request closed without merging**
