### PR TITLE
[Dialogs] Limit Action Button width

### LINKED ISSUE #9150: [Dialogs] MDCAlertController clips wide buttons
## Reproduction steps

1. Present a MDCAlertController with an action with a very long title.
2. Observe that the action button is too wide to fit in the alert.

The following code will reproduce the issue:
```
MDCAlertController *alertController =
    [MDCAlertController alertControllerWithTitle:@"Title" message:@"Message"];
MDCAlertAction *alertAction = [MDCAlertAction
    actionWithTitle:
        @"Very very very very very very very very very very very very very long button name"
            handler:^(MDCAlertAction *action) {
              NSLog(@"Action selected.");
            }];
[alertController addAction:alertAction];
[presentingController presentViewController:alertController animated:YES completion:nil];
```

The above code will render an alert that looks like this:
Reproduced

## Expected behavior

The width of the alert buttons should be limited to the width of the alert. This will allow the buttons to truncate instead of being clipped by the edges of the alert.

I expect the above alert to render like this:
Fixed

## Actual behavior

The alert's buttons are sized to fit, meaning there is no limit on how wide they can be, and they are vertically centered. This causes the buttons to grow beyond the width of the alert, and the sides are clipped.

## Platform (please complete the following information)

 - Device: Any
 - OS: Any

---
#### Internal data
- Associated internal bug: [b/145805150](http://b/145805150)

### PR DESCRIPTION
**Pull request by bambaragoogle**
Changing MDCAlertControllerView to restrict the width of buttons that grow wider than the width of the alert. This happens with long button names, or if the user has a large Dynamic Type setting. Button widths are constrained by the width of the alert minus the horizonal MDCDialogActionsInsets.

Fixes #9150

### CODE REVIEW

**Review by romoore — CHANGES_REQUESTED** [review]
Thanks for the PR, @bambaragoogle .  It looks like a few more things are necessary for this PR to land:

1.  An Issue should be filed detailing the problematic condition and hopefully with a screenshot showing the oversized buttons.
2.  Snapshot tests should be put in place (ideally before this PR) to capture the incorrect behavior.
3. This PR lands and the snapshot images are updated showing the corrected behavior.

If you need help with any of these things, please reach out to us and we can assist or advise.

**Comment by bambaragoogle** [comment]
This PR is related to: https://github.com/material-components/material-components-ios/issues/9150

**Review by romoore — CHANGES_REQUESTED** [review]
Looks like the images might not have been added correctly to Git LFS.

**Comment by bambaragoogle** [comment]
PR to add the tests is https://github.com/material-components/material-components-ios/pull/9154/files. This PR has been updated with new golden images for those tests.

**Comment by bambaragoogle** [comment]
Oops, I changed this to use git-lfs and removed the binary files from the commit history.

**Review by romoore — APPROVED** [review]
LGTM. Thanks for the PR!

**Review by andrewoverton — APPROVED** [review]

**Pull request merged**
