### PR TITLE
Hotfix Release candidate

### PR DESCRIPTION
**Pull request by randallli**
# 25.1.1

Hotfix: Cherry picked: [[Buttons] Call designated initializer in init methods](https://github.com/material-components/material-components-ios/pull/1553)

#### Changes

* [Call designated initializer in init methods (#1553)](https://github.com/material-components/material-components-ios/commit/6f2709de8c8cfd2874934abf293cb7e9b2864368) (ianegordon)

### CODE REVIEW

**Comment by ianegordon** [comment]
In the MDCCatalog workspace, delete EarlGreyTests.swift under MDCEarlGreyTests. (Renaming artifact)  
Doing so gets the test pass working as expected.
With that change, LGTM.

**Comment by willlarche** [comment]
@ianegordon I didn't test locally but that does sound correct.

**Review by ianegordon — CHANGES_REQUESTED** [review]
See note about EarlGreyTests.swift.

**Comment by randallli** [comment]
deleted earl grey file.

**Review by ianegordon — APPROVED** [review]

**Pull request merged**
