### PR TITLE
[TextFields] Add Hindi snapshot tests.

### PR DESCRIPTION
**Pull request by romoore**
Adding snapshot tests for Hindi script across multiple controller styles.
Tests are based on existing Arabic tests and use the same controller styles.

Part of #5762

### CODE REVIEW

**Comment by codeman7** [comment]
Similar question to #6147, I am confused why we need to test multiple LTR languages?

**Comment by codeman7** [comment]
Why was the [Snapshot] label removed?

**Comment by romoore** [comment]
The `[Snapshot]` label is for the Snapshot component in `components/private/Snapshot`. We don't currently have a label unique to snapshot tests within other components.

**Comment by romoore** [comment]
LTR and RTL are not the only important things to test. Alignment with baseline of scripts, ascender/descender heights and overlaps with other UI elements, and any potential manual calculation of widths/heights can be impacted by the choice of script.  In the case of Hindi, there are several rendered glyphs that are made up of multiple "characters". Depending on how we perform layout within the components, these different scripts can interact differently with the layout.

**Review by rami-a — APPROVED** [review]

**Pull request merged**
