### PR TITLE
[Shape] add support for NSCopying

### LINKED ISSUE #5880: [Shape] Make ShapeScheme support NSCopying
## Feature Request/Suggestion

Make shapeScheme support NSCopying would help clients/developers to create a copy of the scheme object.

## Additional context

Color and Typography parts were done.

---
#### Internal data
- Associated internal bug: [b/121040062](http://b/121040062)

### PR DESCRIPTION
**Pull request by fluxminds**
closes https://github.com/material-components/material-components-ios/issues/5880.

Add NSCopying support to MDCShapeScheme would facilitate developers to create their copies of MDCShapeScheme instances.

### CODE REVIEW

**Review by romoore — CHANGES_REQUESTED** [review]
I think it is better to only make the Shape scheme support NCCopying. Please split out the shape changes to other PRs. Just like copying an NSArray of objects, I think it is acceptable to perform a shallow copy if that is all Shapes support for now.

**Comment by fluxminds** [comment]
@romoore I am fine with either shadow or deep copy. MDCColorScheme and MDCTypography use deep copy right now (though UIColor/UIFont doesn't do things, I think it might be good for Shape to try to keep consistent with them?

**Comment by yarneo** [comment]
I agree with @wenyuzhang666 on this one. Making the copy apply fully to the Shape Scheme makes sense, otherwise you are technically just doing half the work.

**Comment by yarneo** [comment]
I agree with @wenyuzhang666 on this one. Making the copy apply fully to the Shape Scheme makes sense, otherwise you are technically just doing half the work.

**Comment by yarneo** [comment]
I agree with @wenyuzhang666 on this one. Making the copy apply fully to the Shape Scheme makes sense, otherwise you are technically just doing half the work. does that make sense?

**Comment by yarneo** [comment]
I agree with @wenyuzhang666 on this one, making the copy apply fully to the Shape Scheme makes sense, otherwise you are technically just doing half the work. does that make sense?

**Comment by fluxminds** [comment]
Rob followed up offline. This PR is split into three PRs. The other two listed here for reference: https://github.com/material-components/material-components-ios/pull/5938, https://github.com/material-components/material-components-ios/pull/5946

**Review by randallli — APPROVED** [review]

**Comment by randallli** [comment]
actually looks like this work was landed as another pr. see conversation history

**Pull request closed without merging**
