### PR TITLE
[ShadowElevations] Add basic snapshot tests.

### LINKED ISSUE #6807: [ShadowElevations] Internal issue: b/128025641
This was filed as an internal issue. If you are a Googler, please visit [b/128025641](http://b/128025641) for more details.

---
#### Internal data
- Associated internal bug: [b/128025641](http://b/128025641)

### PR DESCRIPTION
**Pull request by romoore**
Adding snapshot tests for all defined elevations using a card.

Closes #6807

### CODE REVIEW

**Review by jverkoey — COMMENTED** [review]
It looks like the shadow is clipping on several of the images; consider increasing the snapshot's margins until the shadow is fully enclosed in the image.

**Review by jverkoey — DISMISSED** [review]
Marking as changes requested for margin sizes.

**Review by jverkoey — APPROVED** [review]
LGTM, though MDCShadowElevationsSnapshotTests/testElevationNavDrawer_11_2@2x.png looks like it may still be clipping the bottom shadow.

**Comment by romoore** [comment]
@jverkoey Extended the margins further. Confirmed using Digital Color Meter that all edges end up as `#CCC` (the background color). Even for Picker/Dialogs, the two elevations with values of 24 dp.

**Pull request merged**
