### PR TITLE
[CocoaPods] adding the framework search paths to the runpath search paths to fix IB_DESIGNABLE auto layout rendering errors

### LINKED ISSUE #2946: [CocoaPods] IB_DESIGNABLE auto layout render issues
When adding an IB_DESIGNABLE component to one of our xibs/storyboards, an error comes up in xcode. The error states that it fails to render and update auto layout status for the UIView due to the MDFInternationalization library not loaded. Reason is image not found. 

I suspect this could be a CocoaPods issue, but this needs further investigation.

---
#### Internal data
- Associated internal bug: [b/140930518](http://b/140930518)

### PR DESCRIPTION
**Pull request by yarneo**
As of now, we get errors when using IB_DESIGNABLE components in XIBs and Storyboards in our Catalog app.

screen shot 2018-02-16 at 2 27 25 pm

This resolves #2946

### CODE REVIEW

**Review by ianegordon — APPROVED** [review]

**Comment by ghost** [comment]
This issue continues to bug me. Is there a clear fix for it?

**Comment by ianegordon** [comment]
Hi @toolmarmel 
This is the PR that fixed the original bug.  If this is still a problem for you, could you verify you are using the latest code, and if so open a new bug?
Many Thanks!

**Comment by majid701** [comment]
Still having this issue. I have updated library to the latest version but still no luck!

**Comment by zakdances** [comment]
Still getting this error with version `89.0.0`

```
error: IB Designables: Failed to render and update auto layout status for HomeDrawerVC (GzA-Nx-2VC): dlopen(MaterialComponents.framework, 1): Library not loaded: @rpath/MDFInternationalization.framework/MDFInternationalization
  Referenced from: MaterialComponents.framework
  Reason: image not found
```

**Comment by romoore** [comment]
Thanks, @zakdances. I added your comment to #2946

**Pull request merged**
