### PR TITLE
[Chips][Snackbar] Making all dynamic font logic consistent with each other.

### LINKED ISSUE #4346: Make all dynamic fonts logic consistent.
We have different ways of achieving the same dynamic font in different places.
We should have one approach to all.

### PR DESCRIPTION
**Pull request by mohammadcazig**
close #4346

### CODE REVIEW

**Review by ianegordon — CHANGES_REQUESTED** [review]
Will fail if someone enables adjustsFont, changes sizeCategory, then disables adjsutsFont?
No, it looks like we are okay.

**Comment by ianegordon** [comment]
This eliminates some duplicated code, which is great.  I think we can refactor a bit to avoid setting the ivar and fold the defaultFont method into the original.  I'll take a pass next week.
Thanks you @mohammadcazig !!!

**Comment by jverkoey** [comment]
@mohammadcazig is no longer on the team so someone will have to take over this PR.

**Comment by jverkoey** [comment]
Closing this and filed https://github.com/material-components/material-components-ios/issues/4368 to track follow up.

**Pull request closed without merging**
