### PR TITLE
[Dialogs] Migrate dialogs to availability

### PR DESCRIPTION
**Pull request by andrewoverton**
Original CL: cl/293702412

### CODE REVIEW

**Review by bryanoltman — APPROVED** [review]
LGTM, probably needs a build file update as well

**Comment by andrewoverton** [comment]
It weirdly did not... :/

**Comment by bryanoltman** [comment]
¯\\\_(ツ)\_/¯

**Review by iberezan — APPROVED** [review]

**Comment by nokeeo** [comment]
@andrewoverton @bryanoltman
> It weirdly did not... :/

I think it was not failing to compile because Dialogs is transitively pulling in the dependency via its dependency on Elevation?

**Pull request merged**
