### PR TITLE
[ButtonBar] Fix insets for the trailing button bar

### LINKED ISSUE #2851: [ButtonBar] Why does MDCButtonBarButton need contentPadding

### LINKED ISSUE #3315: [ButtonBar] Paddings are wrong for trailing button bars
Trailing button bars on MDCNavigationBar have an incorrect notion of "first" and "last" button when building the buttons. The inset/padding logic below works fine for leading button bars, but on trailing button bars, the first button is still on the outer edge, which is the right side for LTR:

https://github.com/material-components/material-components-ios/blob/0797becc18f005263dfe72eb75e63246948c11e6/components/ButtonBar/src/private/MDCAppBarButtonBarBuilder.m#L182

In LTR, this issue leads to the left-most button on the trailing button bar to have additional inset on the right side, and the right-most button to have additional inset on the left side.

Internal discussion about this is in b/77863407.

### PR DESCRIPTION
**Pull request by AlimoRabbani**
Fix button insets used in MDCNavigationBar's trailing button bar. 

Internal testing of this PR is done in cl/192473549.

closes #2851
closes #3315

### CODE REVIEW

**Comment by AlimoRabbani** [comment]
The test failures are legitimate. I'll fix them and send a new commit.

**Comment by AlimoRabbani** [comment]
The test that was failing must be fixed in the new commit. I also added a new unit test.

**Comment by jverkoey** [comment]
Add before/after screenshots from the catalog please and a link to any internal cls that tested the behavior.

**Comment by AlimoRabbani** [comment]
This PR should only affect navigation bars that have more than one image button in the trailing button bar. I can't find any such examples in catalog.

Trailing button bars with one image button used to get correct insets, because the single button was both the first button and the last button. Although the insets were reverted on left/right, the final result was correct, since left/right insets are equal.

I added cl/192473549 to the description and some screenshots in b/77863407.

**Comment by AlimoRabbani** [comment]
Internal testing of this PR is finished. We're good to go.

**Comment by jverkoey** [comment]
Can you confirm that the internal screenshot tests that will fail with this PR are intentional changes to correct behavior?

**Review by jverkoey — APPROVED** [review]

**Comment by AlimoRabbani** [comment]
Correct. Commented internally as well for more clarity.

**Comment by jverkoey** [comment]
Thank you! This will go out in tomorrow's release.

**Pull request merged**
