### PR TITLE
[UIApplication] Use prefix on category name for UIApplication+AppExtensions so that category names don't conflict in ObjC namespace.

### PR DESCRIPTION
**Pull request by randallli**
[UIApplication] Use prefix on category name for UIApplication+AppExtensions so that category names don't conflict in ObjC namespace.

sourced from cl/285233749

### CODE REVIEW

**Comment by randallli** [comment]
@googlebot I manually check CLA

**Review by romoore — APPROVED** [review]

**Comment by randallli** [comment]
@googlebot I checked CLA

**Comment by randallli** [comment]
@googlebot I checked CLA
--

**Comment by randallli** [comment]
@googlebot I checked CLA

**Pull request merged**
