### PR TITLE
[Dialogs] Graduate Dialogs theming extensions to ready

### LINKED ISSUE #7163: [Chips] Mark Dialogs theming extension ready
This was filed as an internal issue. If you are a Googler, please visit [b/130718428](http://b/130718428) for more details.

---
#### Internal data
- Associated internal bug: [b/130718428](http://b/130718428)

### PR DESCRIPTION
**Pull request by andrewoverton**
This PR updates the dialogs theming extensions to ready.

Closes #7163.

### CODE REVIEW

**Review by jverkoey — CHANGES_REQUESTED** [review]
It looks like the README needs to be updated as well: https://github.com/material-components/material-components-ios/tree/develop/components/Dialogs#extensions

Please remove any references to beta theming extensions throughout the documentation.

**Comment by andrewoverton** [comment]
Yes, I'm working on it, thanks!

**Comment by jverkoey** [comment]
Please add the docs updates from #7209 to this PR.

**Comment by andrewoverton** [comment]
@jverkoey, I just merged #7209, so I believe this is ready for another look.

**Review by jverkoey — APPROVED** [review]

**Pull request merged**
