### PR TITLE
[ProgressView] Backward animation support

### LINKED ISSUE #969: Allow backwards animation of linear progress view
When setting `MDCProgressView` to a progress less than its current value, the progress bar resets its progress to 0 and then animates from the origin. This might be useful behavior in many cases, but it seems like there should at least be an option to allow backward animations.

[Code in question](https://github.com/material-components/material-components-ios/blob/45c0b06275e88c65c7aae8bba1b78889cba2f93c/components/ProgressView/src/MDCProgressView.m#L135)

The feature request is to add a mode that would default to the current behavior and would include a second value that would animate backwards when the progress value is set to something less than its current value. `MDCProgressBackwardsMode`?

### PR DESCRIPTION
**Pull request by samsymons**
This PR adds backward animation support to the progress view by way of a new `MDCProgressViewBackwardProgressAnimationMode` enum.

By default the progress view will use `MDCProgressViewBackwardProgressAnimationModeReset` which maintains the current behaviour, but using the `MDCProgressViewBackwardProgressAnimationModeAnimate` will cause the progress view to animate backwards when being set with lower progress values.

These enum names are subject to change, they're a little wordy. 😄 

Closes #969.

### CODE REVIEW

**Comment by samsymons** [comment]
Looks like `testPresenceOfKeyWindow` failed — tested locally with success.

**Comment by ajsecord** [comment]
Great! Testing locally...

**Comment by ajsecord** [comment]
I chose a shorter name and changed the "animate" example to match the "reset" example so it's easier to see the difference. What do you think?

**Comment by samsymons** [comment]
@ajsecord Nice, that enum name is easier to handle. I'm also happy to use the same demo — those changes look good to me! 👍

**Pull request merged**
