### PR TITLE
[BottomAppBar] Add the button color themer

### PR DESCRIPTION
**Pull request by ulukaya**
#### Don't forget:
- [ ] Identify the component the PR relates to in brackets in the title. ```[Buttons] Updated documentation```
- [ ] Link to GitHub issues it solves. ```closes #1234```
- [ ] Sign the CLA bot. You can do this once the pull request is submitted.

[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.

### CODE REVIEW

**Review by ajsecord — APPROVED** [review]
Thanks! I'm confused how this didn't break our continuous integration?

**Comment by yarneo** [comment]
Because theming the color of the floating button in the BottomAppBar is optional and not part of the default implementation and usage

**Comment by ianegordon** [comment]
So should this be pulled into the BottomAppBarThemer?
The existing dependency on NavBar+ColorThemer could be replaced with a simple setColor.

**Comment by yarneo** [comment]
BottomAppBar doesn't have a themer as it stands, but maybe now will be a great opportunity to make one that encapsulates these subcomponent themings.

**Comment by ianegordon** [comment]
Hi @ulukaya, thanks for the PR!

Typically we wouldn't expect a component to depend on a Themer.  Themers can (must) rely on components, but components should not rely on Themers.

Can you show an example of what you are trying to do? (I feel like there was originally an example, but it seems to have disappeared)

As an alternative to this change to the podspec, can you add the dependency directly to your Podfile?

I've opened an issue to remove BottomAppBar's existing dependency on the NavigationBarThemer #2806.
I've also opened an issue to provide a full BottomAppBarThemer #2807 .

**Review by ianegordon — CHANGES_REQUESTED** [review]
Blocked while we do a quick investigation of some alternatives.

**Comment by romoore** [comment]
Just my two cents:
*  BottomAppBar needs a new colorThemer which excludes the FAB (#2279)
* FAB should be themed using UIAppearance containment and the existing MDCButtonColorThemer (iOS 8+ Objective-C, iOS 9+ Swift).

**Comment by jverkoey** [comment]
Thank you for the PR ulukaya. We are pursuing themers in a systematic way across all of our components right now. I am closing this PR because it hasn't had any movement in more than a month.

**Pull request closed without merging**
