### PR TITLE
[Shapes] Remove MDCShapedShadowLayer fillColor property

### PR DESCRIPTION
**Pull request by samnm**

### CODE REVIEW

**Review by jverkoey — APPROVED** [review]

**Comment by jverkoey** [comment]
```
ERROR: /Volumes/BuildData/tmpfs/src/github/repo/components/private/Shapes/BUILD:23:1: C++ compilation of rule '//components/private/Shapes:Shapes' failed (Exit 1).
components/private/Shapes/src/MDCShapedView.m:38:55: error: property 'fillColor' not found on object of type 'MDCShapedShadowLayer *'
    _fillColor = [UIColor colorWithCGColor:self.layer.fillColor];
                                                      ^
components/private/Shapes/src/MDCShapedView.m:79:14: error: property 'fillColor' not found on object of type 'MDCShapedShadowLayer *'
  self.layer.fillColor = backgroundColor.CGColor;
             ^
```

**Comment by samnm** [comment]
Oops. Fixed.

**Comment by jverkoey** [comment]
@romoore Nice work with the bazel integrations - already seeing the faster turnaround benefits :)

**Comment by romoore** [comment]
Closes to #2704 and #2705

**Pull request merged**
