### PR TITLE
[BottomNavigation] Add a titles-only example.

### PR DESCRIPTION
**Pull request by jverkoey**
This example is a Dragon. This example is in service to testing accessibility of this component.

Screen Shot 2019-06-03 at 9 02 54 AM

### CODE REVIEW

**Review by andrewoverton — APPROVED** [review]

**Review by romoore — DISMISSED** [review]
I don't see this changing the Titles.  Please make sure that selected titles are somehow different from unselected titles. Without images (or other non-color changes), this example will be difficult to use for individuals with atypical in color vision.

**Comment by romoore** [comment]
Since this example will be explicitly inaccessible, I'd like to understand why we're creating it. It doesn't seem to demonstrate a bug/defect or any other features.  The description implies testing accessibility, but since it's being made inaccessible, I don't quite understand.

**Review by romoore — CHANGES_REQUESTED** [review]
Please do not dismiss blocking reviews unless the reviewer is unavailable or it's time-critical.

**Comment by jverkoey** [comment]
Closing this PR because it's not something in our guidelines and we don't want to encourage it as a pattern.

**Pull request closed without merging**
