### PR TITLE
[NavigationDrawer] Allow users to scroll to dismiss on lower resolution devices.

### LINKED ISSUE #8454: [BottomNavigation] Internal issue: b/137218552
This was filed as an internal issue. If you are a Googler, please visit [b/137218552](http://b/137218552) for more details.

---
#### Internal data
- Associated internal bug: [b/137218552](http://b/137218552)

### PR DESCRIPTION
**Pull request by codeman7**
This change allows `currentlyFullscreen` property on [`MDCBottomDrawerContainerViewController`](https://github.com/material-components/material-components-ios/blob/develop/components/NavigationDrawer/src/private/MDCBottomDrawerContainerViewController.m) to become `NO` on lower resolution devices. Currently this property is always `NO`. This doesn't allow the code within `- (void)scrollViewWillEndDragging:withVelocity:targetContentOffset:` to be executed.

## Testing
1. Set `preferredContentSize` on the headerVC of a Navigation Drawer example to 80.
2. Set `preferredContentSize` on the contentVC of the same Navigation Drawer example to a value less than 240. 
3. Open the example on a iPhoneSE
4. Rotate to landscape.
5. Try to swipe to dismiss the drawer.

Closes #8454

### CODE REVIEW

**Comment by yarneo** [comment]
Could you please provide some documentation around the addition to explain why we need this change and what it means

**Comment by codeman7** [comment]
@yarneo I've added documentation please let me know if further clarification is needed.

**Comment by yarneo** [comment]
Just want to clarify:
prior to this change: currentlyFullscreen was always NO for lower resolution devices at all times? Landscape and Portrait, and when being deep into the content scroll view?

Do you believe maybe that your added change is possibly the only needed conditional and 
self.contentReachesFullscreen && headerTransitionToTop >= 1 can be removed?

**Comment by codeman7** [comment]
@yarneo `headerTransitionToTop >= 1` can be removed but `self.contentReachesFullScreen` cannot.

**Review by yarneo — APPROVED** [review]
Thanks. please make sure we haven't regressed with high res devices with this fix. good work

**Comment by codeman7** [comment]
@yarneo I tested on high res devices and it looks good to me.

**Pull request merged**
