### PR TITLE
Remove CocoaPods attributions from our README.md.

### PR DESCRIPTION
**Pull request by jverkoey**
Attributions for downstream dependencies must be handled at the app level and presented at runtime in an app open source attributions page. This is not the responsibility of our README.md.

### CODE REVIEW

**Comment by ianegordon** [comment]
To my fellow MUXers, please allow @ajsecord to approve / merge this PR.

**Comment by ajsecord** [comment]
I believe it is important to allow users to see what other legal requirements they are agreeing to if they use the library. Is there more context you could share? Your statement about the app's responsibilities is correct.

**Comment by jverkoey** [comment]
That's understandable. Historically I haven't seen READMEs bear the brunt of this communication though. The implication is that if we do feel like we want to do this, then we should be adding every dependency of MDC to the readme (this is where I think it gets unsustainable), notably all of the foundation and material motion deps.

**Comment by ajsecord** [comment]
100% agree. Adding a new dependency is a super heavy decision, we _should_ have to think about it... I actually think this is WAI. Can we add the missing ones?

**Comment by jverkoey** [comment]
I'm not sure I totally agree that this extra process will help influence our decisions on whether to add a dependency — I unfortunately think it's more likely that we'll just forget to update the README (as we have done for the past few years/dependencies). I think I'm still leaning towards removing it and deferring to client teams to manage their final attributions.

**Comment by jverkoey** [comment]
Closing for now.

**Pull request closed without merging**
