### PR TITLE
[BottomNavigation] Add accessibilityHint support in the tab bar item view.

### LINKED ISSUE #7290: [BottomNavigation] UITabBarItem.accessibilityHint not assigned to item view
The `accessibilityHint` of the UITabBarItem is not being correctly passed through to the (button in) the item view. Users should be able to set the `accessibilityHint` of the item and VoiceOver should read it out.  Similarly, the value should be Key-Value Observed so changes are propagated to the item even after assignment.

---
#### Internal data
- Associated internal bug: [b/132166866](http://b/132166866)

### PR DESCRIPTION
**Pull request by donaldhu**
Propagate a `MDCBottomNavigationItemView`'s accessibilityHint to its `button`.

Closes #7290 

Steps for manually testing:
1. Turn on Voice Over.
2. Open the "Bottom Navigation" example.
3. Make Voice Over focus on the "Reader" tab (4th item from left).
4. If the Reader tab is unselected, ensure that it reads "Reader, 88, Tab, 4 of 5 - Shows the reader screen." (Note: there is a delay between "4 of 5" and "Shows the reader." This is expected and consistent with Apple's `UITabBar`.)
5. Select the Reader tab. Ensure it reads "Selected, Reader, 88, Tab, 4 of 5." (Note: it does not read the hint here, which is expected and consistent with Apple's `UITabBar` behavior.)

### CODE REVIEW

**Comment by donaldhu** [comment]
I signed it!

**Comment by donaldhu** [comment]
I signed it!

**Comment by donaldhu** [comment]
Adding another comment to kick off googlebot cla check.

**Review by romoore — APPROVED** [review]
Thanks, @donaldhu . The change looks good. I know UIAccessibility is nearly impossible to test in unit (logic) tests. Could you please include in your PR description the steps you're taking to manually test this change?   Ideally, it would be some set of steps for using the MDC Catalog.

**Comment by donaldhu** [comment]
@romoore, I added steps to manually test the accessibility hint to the PR's description.

**Review by romoore — APPROVED** [review]
Looks good. Tested using provided steps and also with an `accessibilityHint` value changed after the UITabBarItem was assigned to the Bottom Navigation bar.

**Comment by romoore** [comment]
Hmm, @donaldhu . I'm finding that when the "Reader" item is selected, it reads out the hint regardless. I think we can merge this as-is (since it's an improvement) and file an Issue to match the `.selected` behavior with UITabBar.

Updated: I verified in a simple Xcode project with a UITabBarController that the hint is read out even on selected items.

**Comment by romoore** [comment]
Looks like a unit test has failed. Not sure whether it's the getter or setter, though.

```
Test Case '-[BottomNavigationTests testAccessibilityHintInitialValue]' started.
components/BottomNavigation/tests/unit/BottomNavigationTests.m:204: error: -[BottomNavigationTests testAccessibilityHintInitialValue] : (([bar.itemViews.firstObject.accessibilityHint isEqualToString:initialHint]) is true) failed
```

**Comment by donaldhu** [comment]
@romoore, do you know how I can get the test build configurations? I would like to be able to execute the same exact test (under the same conditions) as when it fails.

When I run the test locally, it passes. And it's strange that the unit test only fails on a specific device.

**Comment by romoore** [comment]
@donaldhu Correct me if I'm wrong, but I suspect you're running on Xcode using CocoaPods as the dependency system.  I've found that in the CocoaPods+Xcode environment, things like UIAccessibility and view hierarchy-related functionality behaves differently. The Kokoro job uses Bazel and strict logic testing.  If you want to test it, you would follow [the instructions to install and run Bazel with MDC-iOS](https://github.com/material-components/material-components-ios/blob/develop/contributing/bazel_kokoro.md). The command to replay these tests locally would be:

```bash
# Executes all tests targets affected by the current branch (versus `develop`).
 ./.kokoro -d bazel-affected
```

```bash
# Executes all test targets in the BottomNavigation component
./.kokoro -d bazel -t //components/BottomNavigation/...
```

When I run the tests locally, I see the same failure:

```
Test Case '-[BottomNavigationTests testAccessibilityHintInitialValue]' started.
components/BottomNavigation/tests/unit/BottomNavigationTests.m:204: error: -[BottomNavigationTests testAccessibilityHintInitialValue] : (([bar.itemViews.firstObject.accessibilityHint isEqualToString:initialHint]) is true) failed
```

**Comment by romoore** [comment]
I've fixed the test logging (I opened #7326 for it). The issue appears to be that the hint is being overridden at some point:

```
Test Case '-[BottomNavigationTests testAccessibilityHintInitialValue]' started.
components/BottomNavigation/tests/unit/BottomNavigationTests.m:204: error: -[BottomNavigationTests testAccessibilityHintInitialValue] : ((bar.itemViews.firstObject.accessibilityHint) equal to (initialHint)) failed: ("1 of 1") is not equal to ("initialHint")
```

**Comment by jverkoey** [comment]
Gentle ping on this PR. Are we still pursuing this?

**Comment by codeman7** [comment]
@donaldhu gentle ping

**Review by romoore — CHANGES_REQUESTED** [review]
Marking this "Changes Requested" until the test failures are corrected.

**Comment by romoore** [comment]
Closing this due to lack of ongoing updates to the PR. Please feel free to reopen when the testing issues have been addressed.

**Pull request closed without merging**
