### PR TITLE
Move the catalog podfile to the root of the repo.

### PR DESCRIPTION
**Pull request by jverkoey**
This allows us to run `pod install` from the repo's root.

### CODE REVIEW

**Review by randallli — COMMENTED** [review]
Why is this better than in the subfolder? why does it matter where we run pod install from?

**Comment by jverkoey** [comment]
Because most git operations happen in the root of the repo. Having to switch between the catalog subfolder and the repo root is a waste of time/effort, and most pod repos have their example Podfile in the root.

**Review by chuga — APPROVED** [review]
LGTM

**Review by chuga — CHANGES_REQUESTED** [review]
LBTM

**Review by chuga — APPROVED** [review]
We should also update the readme(s), I bet we have references to /catalog

**Comment by jverkoey** [comment]
Good call @chuga. Fixed more paths.

**Review by ajsecord — CHANGES_REQUESTED** [review]
Please don't do this—isolate the catalog from the rest of the lib as much as possible. A bare Podfile at the root of the library is very confusing, and we have many Podfiles, not just catalog's. 

Also, git works fine anywhere in a repo, the root isn't special...

**Comment by jverkoey** [comment]
As best I can tell, this change doesn’t change the catalog’s relationship with our lib - can you elaborate on your concern? With the information I have right now this is a fairly small/trivial change that will make general day-to-day component work more frictionless (that we have to include an extra arg to our pod install is a good indicator that we’re doing something nonstandard here).

**Comment by ajsecord** [comment]
- There are five apps that have Podfiles in the repo, not just catalog.
- The root is already awfully messy.
- Is this for Kokoro or other script-y things? That should be using the infra we already have built in `scripts/` like `prep_all` or `manage_pods`.
- Catalog isn't special enough to warrant being in the root.
- I'm assuming there are a lot of docs/codelabs that refer to the catalog folder. You've looked locally, but what about across the web?

This isn't worth the engineering time, imho.

**Comment by jverkoey** [comment]
Ah well - certainly not worth the debate! I wager once we've migrated to bazel fully we'll find it to be more efficient to do day-to-day development with tulsi, so this change isn't particularly important.

**Pull request closed without merging**
