### PR TITLE
[ButtonBar] Make left/right insets for image and text buttons consistent

### LINKED ISSUE #3342: [NavigationBar] Inconsistent left/right insets and ink style for text buttons
Text buttons used in the button bars of MDCNavigationBar have different left/right insets compared to image buttons. Therefore, a navigation bar that has text buttons beside an image button looks awkward due to inconsistent insets.

Also, the ink style used for text buttons is different than the one used for image buttons.

I can't seem to find guidelines about these in the material spec, but I wonder if we should make them consistent?

https://github.com/material-components/material-components-ios/blob/0ad1f5dfb29cb6ff63b47085c7d33ece0610a0c7/components/ButtonBar/src/private/MDCAppBarButtonBarBuilder.m#L40

---

Pivotal story: https://www.pivotaltracker.com/story/show/156777752

### PR DESCRIPTION
**Pull request by AlimoRabbani**
Internal testing of this PR is done in cl/193415210. This is a behavior change for text button insets in MDCButtonBar.

NOTE: This doesn't *change* insets for text buttons that are the only button in the bar on iPad, since it still adds a 12pt inset on both sides for it. on iPhone, the additional inset for edge buttons is 4pt, which results in a 16pt inset on the edge side(s).

Before screenshots:
[Text buttons on both sides](https://user-images.githubusercontent.com/2232489/38957009-57ca20fa-4327-11e8-9f62-a92a61c7f20f.png)
[Text button on one side](https://user-images.githubusercontent.com/2232489/38957010-57d6b784-4327-11e8-8971-2c565833052d.png)

After screenshots:
[Text buttons on both sides](https://user-images.githubusercontent.com/2232489/38957016-5c719ee4-4327-11e8-886c-a7b6bdece4b5.png)
[Text button on one side](https://user-images.githubusercontent.com/2232489/38957017-5c7ebd36-4327-11e8-868b-5fde087eb382.png)

closes #3342

### CODE REVIEW

**Comment by jverkoey** [comment]
I also can't find any guidance on these metrics in the spec, so for the time being I think it's reasonable to optimize for space utilization.

**Review by jverkoey — APPROVED** [review]
LGTM, with caveat that this is a moderate-to-high risk of internal screenshot regressions.

**Comment by ianegordon** [comment]
This change LGTM, thanks for putting together the PR.
This will definitely cause screen test failures.
As @jverkoey is handling the releases right now, I'll leave it to him to choose when to merge.

**Comment by AlimoRabbani** [comment]
Internal testing of this PR is now done and approved in cl/193415210.

**Pull request merged**
