### PR TITLE
[BottomNavigation] Remove duplicate tab position descriptions

### PR DESCRIPTION
**Pull request by romoore**
When adding the UIAccessibilityTraitTabBar to MDCBottomNavigationBar, don't add custom "tab" and "1 of 4" strings.

### CODE REVIEW

**Comment by romoore** [comment]
All authors have signed the cla.

**Comment by romoore** [comment]
The original commit author (not merge commits) are from a Googler making a contribution internally. This is an exported PR reflecting that internal change.

cl/206817660

**Comment by jverkoey** [comment]
Am assuming then that the UIKit API that we’re looking up here will handle accessibility as expected?

**Review by jverkoey — APPROVED** [review]

**Comment by romoore** [comment]
Not yet tested on iOS 8 or 9 - I need a device that with iOS version to test.

**Comment by romoore** [comment]
Tested on iPhone 4s/iOS 8.3 and it read out the "1 of 5" correctly in VoiceOver.

**Pull request merged**
