### PR TITLE
[Ripple] Don't dissolve the ripple if the highlighted state is still set to YES.

### PR DESCRIPTION
**Pull request by yarneo**
As part of the effort for: #7268 to integrate Ripple into Chips, this improvement is added into the Ripple component.

An addition of a stronger and more accurate conditional in the isHighlighted implementation of MDCStatefulRippleView to ensure that we are not dissolving the Ripple unless the highlighted state is set to NO.

This should land prior to #7270 to make sure that the Ripple integration with Chips has this improvement to ensure a smooth and correct integration.

### CODE REVIEW

**Review by jverkoey — COMMENTED** [review]
Are there any tests affected by this change? If not please add some to make sure we don't regress on this functionality.

**Comment by romoore** [comment]
+1 to what @jverkoey said.  It sounds like a Snapshot test would be appropriate here. If you put the test through in a separate PR, we can capture exactly when the Ripple dissipates (and when it does not) before and after this change is made.

**Comment by yarneo** [comment]
opened #7279 as the snapshot test to test this. Once that lands i'm expecting a delta of that snapshot in this PR.

**Review by jverkoey — APPROVED** [review]
LGTM on the assumption that once #7279 lands this PR won't need to be substantially updated. If it does, though, please re-add me for review.

**Comment by jverkoey** [comment]
Holy orange batman! Is that the expected color?

**Comment by yarneo** [comment]
haha yeah that's intended. I made the color very distinct so it will be easy to differentiate that the fix did change the result of the snapshot test.

**Pull request merged**
