### PR TITLE
[HeaderStackView] Remove the header stack view examples.

### PR DESCRIPTION
**Pull request by jverkoey**
This component is not generally intended to be used beyond the App Bar. Any examples of header stack view should live in the app bar component's examples instead.

Closes https://github.com/material-components/material-components-ios/issues/655

### CODE REVIEW

**Comment by romoore** [comment]
Based on the summary, I would expect to just update the breadcrumbs for these? Maybe make them Dragons?

**Comment by romoore** [comment]
Also, if clients should not be using HSV, we should move it to the "private" components folder.

**Comment by jverkoey** [comment]
They are currently dragons, but they’re worse than dragons.

**Comment by jverkoey** [comment]
Agreed - but that’s beyond the scope of this change.

**Comment by jverkoey** [comment]
https://github.com/material-components/material-components-ios/issues/4812 to track work on moving the HeaderStackView to a private component status.

**Comment by randallli** [comment]
If its a private component is there value in having examples on how to use it?

**Review by randallli — APPROVED** [review]

**Comment by romoore** [comment]
I still think having examples in Dragons is worthwhile. The fact that few contributors know how it works makes it risky if @jverkoey ever goes on to another project.

**Comment by jverkoey** [comment]
The examples are the AppBar examples.

**Comment by romoore** [comment]
The AppBar examples show how to use the AppBar, not how to use the HSV as a standalone component.  Even if it becomes a private component some day, I think it's useful for developers (us) to understand how to use it and have Dragons around its capabilities. What's the risk of keeping at least some of the Dragons for maintainers to explore?

**Comment by jverkoey** [comment]
Nearly all of the header stack view behavior is implemented on the assumption that it will be placed inside of an App Bar, so its existence as a standalone API is simply incorrect. There is no situation that we knowingly support in which someone would use a header stack view other than from within an App Bar.

**Pull request merged**
