### PR TITLE
[AnimationTiming] Add the sharp curve.

### PR DESCRIPTION
**Pull request by codeman7**
Update Animation timing to include the sharp curve. Also, updates the names to that of the spec.

### CODE REVIEW

**Comment by willlarche** [comment]
I like it but it would cause a lot of changes. Let me get a higher up approval. @ajsecord ?

**Comment by codeman7** [comment]
Yeah figure this kind of change takes MDC-iOS to 39.0. We could keep the names the same so we don’t break anything but then naming the sharp curve is problematic. We could have EaseIn, EaseOut, EaseInOut, EaseoutIn but I can see how that causes issues when clients use MDC.

**Comment by jverkoey** [comment]
If we decide to move forward with this change then we will need to do it in the following phases:

1. Introduce the new APIs. The old APIs should be aliased to the new APIs. This change will not cause a major version bump and will allow client teams to move to the new APIs.
2. After some time, deprecated the old APIs.
3. Remove the old APIs once all Google clients have migrated off the old APIs.

As the TL for Material Motion I agree that naming-wise we should be consistent with the Material Spec and approve of the direction of these changes.

**Comment by jverkoey** [comment]
Alternatively, a faster path to getting the new API landed would be to revert the API name changes and only add the new API. Up to you!

**Review by jverkoey — CHANGES_REQUESTED** [review]
This PR is doing two things, so let's split it apart:

- [ ] One PR introducing the new API.
- [ ] One PR moving the APIs to the new names.

**Comment by ajsecord** [comment]
For deprecations, you can read more about how we do things [here](https://github.com/material-components/material-components-ios/blob/aeb8cb09a3d9f58efa9a9d28c521e0673fc29106/contributing/deprecation_policy.md). This has worked relatively well for us in the past. This is kind of formal, but the general approach is sound.

As for the naming, I think @randallli was involved in the original naming, and that there were some surprising issues around naming these curves. Randall, am I remembering correctly?

**Comment by randallli** [comment]
The names @codeman7 is using are in the public spec:
https://material.io/guidelines/motion/duration-easing.html#duration-easing-natural-easing-curves

When we internally renamed these last time I was bringing them closer to the native names with similar shape (easeInOut, easeIn, etc). I still think those names are still useful and would keep them around as aliases.

**Comment by jverkoey** [comment]
Spoke offline with @randallli: we're in agreement that moving towards matching the spec's API names is desirable, and that moving away from the easing metaphor will help distinguish the material motion timing curves from the system curves.

Given that, my original "changes requested" comment still applies and we'd love to see this move forward as two separate PRs.

**Comment by codeman7** [comment]
@jverkoey I can't see what's going on with Travis on the last build it just shows that it didn't pass. Also, I assume the cla will be ok since you authored the commit, right?

**Comment by romoore** [comment]
@codeman7 It seems one of the 4 build jobs stalled. I've restarted the stalled job.

**Review by randallli — APPROVED** [review]

**Review by jverkoey — APPROVED** [review]

**Comment by jverkoey** [comment]
Tested locally that the build is ok. Kokoro failed because the PR hasn't been synced to the latest develop.

**Pull request merged**
