### PR TITLE
Make the team handbook appear on material.io

### PR DESCRIPTION
**Pull request by jverkoey**
- Content is now organized into rough chapters of information.
- Our team handbook should now appear on material.io.

### CODE REVIEW

**Review by yarneo — APPROVED** [review]
make sure all the headers path: section is supposed to be prefixed with /docs/ and not /contributing/

**Comment by jverkoey** [comment]
This change does intentionally separate the top-level "contributing" doc from the team handbook. The intent is for the team handbook to be a top-level document alongside components + documentation.

**Comment by jverkoey** [comment]
This is blocked on me being able to generate the site locally in order to ensure I didn't massively break anything >.<

**Comment by jverkoey** [comment]
This is blocked by us being able to generate the website locally in order to preview changes, so I'm closing this PR.

**Pull request closed without merging**
