### PR TITLE
[WIP] [ChipTextField] Use MDCChipTextFieldScrollView to replace leftView functionality for flexibility and extensibility

### PR DESCRIPTION
**Pull request by fluxminds**
This PR is reverting: #6167 which was reverted in a release because of presubmit issue.

This PR is dependent on https://github.com/material-components/material-components-ios/pull/6035. And there is no new API change on MDCChipTextField class level.

This PR is meant to solve the problem mentioned in https://github.com/material-components/material-components-ios/pull/6035 -> "Enabling scrolling of the Chips and the remaining alignment issues will be resolved in followup PRs." 
The issues it solves:
(1) Alignment (a way to adjust it also)
(2) clear button
(3) the coupling issue with apple's leftView in the original PR.

Some remaining problem with the original issues (Will be updated in the TODO in the code too):
(1) The chip removal indentation doesn't work well (Solvable by adding an additional constraint).
(2) The scrolling behavior of Chips was not added (Shouldn't be hard to add on this base - 1 day workload, but needs confirmation from design, it's probably not a feature we want to support right now)
(3) Fix a hack number added on https://github.com/material-components/material-components-ios/pull/6167/files#diff-6c02a09694ee9585406c9dc9da7621efR117.
(4) A known bug where the space between text and clear button is uncertain when the chip is very long, it should be automatically resolved after solving (3).
(5) RTL is not the purpose of this PR. It will be included in https://github.com/material-components/material-components-ios/pull/6035
(6) Screenshot Testing is not the purpose of this PR, but it will be very helpful. Something to work on after solving (1) and (3).

Screenshots:
simulator screen shot - iphone xs - 2019-01-02 at 11 30 50
simulator screen shot - iphone xs - 2019-01-02 at 11 30 54
simulator screen shot - iphone xs - 2019-01-02 at 11 30 57

### CODE REVIEW

**Comment by romoore** [comment]
@wenyuzhang666  Is this a "WIP" PR? It looks like it's missing a summary. Could you please add a summary or mark it WIP if it's not yet ready for review?

**Comment by fluxminds** [comment]
@romoore I thought I marked WIP before.

**Comment by romoore** [comment]
@wenyuzhang666 It's been open for a long time and I was going through open PRs trying to see what could be reviewed/merged/closed.  You may want to consider reopening this as a Draft PR if it's not close to review.

**Comment by fluxminds** [comment]
@romoore yea, it was open for a long time. I changed the description is waiting on Galia's one to merge before removing the WIP on this PR. I will probably a new PR too. Thanks for checking and going through these PRs.

**Pull request closed without merging**
