### PR TITLE
[WIP] Flakiness testing at head

### PR DESCRIPTION
**Pull request by jverkoey**

### CODE REVIEW

**Comment by jverkoey** [comment]
Last run did not flake.

**Comment by jverkoey** [comment]
Last run did not flake.

**Comment by jverkoey** [comment]
Last run did not flake.

**Comment by jverkoey** [comment]
We have a flake!

https://fusion.corp.google.com/runanalysis/test/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_xcode_900/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_xcode_900/KOKORO/15a028d3-7a91-46e7-8a1e-7340fd80fce7/1523577346820/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_xcode_900%20Build%20%23225/Target%20Transitions?target=MaterialComponents_iOS/macos_external/presubmit_bazel_xcode_900

Unfortunately this is a completely new flake and possibly unrelated to anything we've been seeing so far. Will continue running presubmits...

```
Test Suite 'SnackbarManagerTests' started at 2018-04-12 17:03:15.108
Test Case '-[SnackbarManagerTests testMessagesResumedWhenTokenIsDeallocated]' started.
Invalid connection: com.apple.coresymbolicationd
<unknown>:0: error: -[SnackbarManagerTests testMessagesResumedWhenTokenIsDeallocated] : Asynchronous wait failed: Exceeded timeout of 1 seconds, with unfulfilled expectations: "completed".
Test Case '-[SnackbarManagerTests testMessagesResumedWhenTokenIsDeallocated]' failed (2.061 seconds).
Test Suite 'SnackbarManagerTests' failed at 2018-04-12 17:03:17.170.
	 Executed 1 test, with 1 failure (0 unexpected) in 2.061 (2.061) seconds
```

**Comment by jverkoey** [comment]
Another flake:

```
ERROR: /Volumes/BuildData/tmpfs/src/github/repo/components/Snackbar/BUILD:91:1: Compiling Swift module unit_test_swift_sources (3 files) failed (Exit 1)
components/Snackbar/tests/unit/MDCSnackbarColorThemerTests.swift:19:8: error: no such module 'components_Snackbar_ColorThemer'
import components_Snackbar_ColorThemer
       ^
INFO: Elapsed time: 237.793s, Critical Path: 20.02s
FAILED: Build did NOT complete successfully
```

Will stop testing this PR now that a flake has been confirmed.

**Comment by romoore** [comment]
The snackbar flake is old and well-known. It's because Swift unit tests take longer to run. I believe we extended the wait time to ~1 seconds from something much shorter. Very disappointing to imagine that the variable isn't being deallocated within 1 second. :-\

**Pull request closed without merging**
