### PR TITLE
[Tutorial] add `@objc` to be called from objc lib

### PR DESCRIPTION
**Pull request by nicechester**
### Thanks for starting a pull request on Material Components!

This is required by Swift 4 and as a iOS dev, you may not have a chance to move back the previous version of XCode.

This fix will resolve ppl struggling with their xcode 9 while following the tutorial.

https://github.com/material-components/material-components-ios/issues/2879

### CODE REVIEW

**Comment by nicechester** [comment]
I signed Google CLA

**Comment by nicechester** [comment]
I don't know what happened.
Here's email I got
```
Will Larche <notifications@github.com> | Will Larche <notifications@github.com> | 2:06 PM (21 hours ago) |   |  
-- | -- | -- | -- | --
Will Larche <notifications@github.com>
to material-compo., me, Mention | to material-compo., me, Mention
to material-compo., me, Mention

@nicechester , We're a little swamped at the moment. Would you be able to do a pull request with changes that fix it? Would be a big help!
```

**Comment by ianegordon** [comment]
Hi @nicechester , thanks for the PR 😄  sorry for the difficulty with the CLA ☹️ 
I've reached out to the clabot team to try and figure out where things are going wrong.  We definitely appreciate your patience.

**Comment by ianegordon** [comment]
Hi Chester, mystery solved.  The commit in question has the author as: chester.kim@disney.com
The CLA you signed was as: violkim@gmail.com

You can either:
```
git commit --amend --author="violkim@gmail.com"
git push --force
```
I believe you can also set the author to "nicechester@users.noreply.github.com

-OR-

I believe there is a way to add another email addess to your signed CLA at:
https://cla.developers.google.com

**Comment by nicechester** [comment]
@ianegordon Uh oh!  I don't want to expose my work email here.  Can you remove it from your comment?

**Comment by ianegordon** [comment]
Hi @nicechester , thanks for the PR!  We'll take a look.

**Review by willlarche — APPROVED** [review]

**Comment by willlarche** [comment]
Thank you!!

**Comment by willlarche** [comment]
Ignoring unfinished Kokoro tests as this is .md file.

**Pull request merged**
