### PR TITLE
[Dialogs] Add property to enable / disable the shadow on the tracking view

### PR DESCRIPTION
**Pull request by ianegordon**
This allows us to enable / disable the shadow that tracks a presented view in MDCDialogPresentationController.  It is implemented in a similar fashion to the existing dismissOnBackgroundTap property.

This is an internal request.

Screenshot from new example:
simulator screen shot - iphone x - 2018-05-17 at 14 28 53

### CODE REVIEW

**Review by jverkoey — DISMISSED** [review]
What is the context requiring the removal of the shadow? This seems like a non-ideal deviation from the component's design intent.

**Comment by jverkoey** [comment]
Looking at the code, it looks like we're adding this API so that the shadow can be customized. Can we support customization in any other manner? Ideally we'd implement such a way that it can be implemented using a themer.

I'm concerned that this boolean parameter will encourage incorrect designs if someone simply disables it.

**Comment by ianegordon** [comment]
The client would like to handle their own shadow as their view / view's shadow path may not be rectangular. Currently we use a rectangular tracking view to cast the shadow as it is part of the 'chrome'.  I don't expect this property will have significant use.  I've added some more explicit documentation.

**Comment by jverkoey** [comment]
The client need makes sense but I’m not convinced that this is an approach that encourages good behavior. Can we expose the shadow layer in some way instead?

**Comment by ianegordon** [comment]
The shadowLayer is an instance of a class-specific MDCShadowLayer ivar in a UIView that is intentionally private. To put it another way, Unfortunately, no :(

Happy to discuss offline if you are curious about the particulars.

**Comment by jverkoey** [comment]
This is being pursued in https://github.com/material-components/material-components-ios/pull/4233.

**Pull request closed without merging**
