### PR TITLE
[Catalog] Commit updated project.pbxprojs

### PR DESCRIPTION
**Pull request by samnm**
Running `pod install` makes some changes to the xcode projects.

### CODE REVIEW

**Comment by ianegordon** [comment]
Do we all need to update to the latest cocoapods?

**Comment by samnm** [comment]
We should, but we don't have to. Unfortunately the newest cocoapods version surfaced some warnings/errors so we should be on the latest version to resolve those.

**Comment by ianegordon** [comment]
Restarted broken Travis Build.

**Review by ianegordon — APPROVED** [review]
Cocoapods update.
Travis is happy.
LGTM.

**Pull request merged**
