### PR TITLE
[NavigationDrawer] Remove bottom drawer container view as child upon dismissal

### PR DESCRIPTION
**Pull request by m-cheung**
This pull request prevents a crash (due to 'UIViewControllerHierarchyInconsistency') that occurs if the user of the NavigationDrawer reuses the view controllers (i.e. they do not create a new view controller that is passed to the NavigationDrawer each time the drawer is presented). #5821 added the bottomDrawerContainer as the child view, and this pull request will remove the bottomDrawerContainer from the parent upon dismissal.

#### Don't forget:
- [ ] Identify the component the PR relates to in brackets in the title. ```[Buttons] Updated documentation```
- [ ] Link to GitHub issues it solves. ```closes #1234```
- [ ] Sign the CLA bot. You can do this once the pull request is opened.

[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.

### CODE REVIEW

**Review by yarneo — CHANGES_REQUESTED** [review]
Thank you for catching that, and for contributing!

Could you please put it under the same conditional when it was added so it only removes it if it was added in the first place:
`if ([self.presentedViewController isKindOfClass:[MDCBottomDrawerViewController class]]) {`

**Comment by m-cheung** [comment]
Whoops, sorry about that. I have made the change as requested. PTAL

**Review by yarneo — APPROVED** [review]
thank you!

**Comment by jverkoey** [comment]
Hi @m-cheung: our CI was broken this morning unfortunately, but we have since fixed the issue. Can you rebase this PR off of develop and force-push please? This will fix the apidiff status bit.

**Comment by romoore** [comment]
@jverkoey Does it not work to merge from `develop` into the PR branch?

**Comment by yarneo** [comment]
It is easily seen that the PR doesn't have any effect on any API, which therefore makes the apidiff bot unnecessary in this case. The PR passes all other tests that are necessary. Will go ahead and merge the PR to offload any additional work from the contributor.

**Pull request merged**
