### PR TITLE
Revert "[Tabs] Disallow tabs that are wider than the screen (#1408)"

### PR DESCRIPTION
**Pull request by brianjmoore**
This change broke a few clients and should be rolled back.

### CODE REVIEW

**Comment by samnm** [comment]
:( What was the break?

**Comment by brianjmoore** [comment]
Note: this also needs to be reverted in the release-candidate branch

**Review by samnm — APPROVED** [review]

**Comment by brianjmoore** [comment]
Centered tabs are centered using sometimes very large insets, which ended up making the maximum width very small and squished all the tabs too much.

**Review by ianegordon — APPROVED** [review]

**Comment by ianegordon** [comment]
This is a mirror of an internal rollback.
I'll merge as soon as Travis / local testing finished.

**Comment by ianegordon** [comment]
Successful local test.

**Pull request merged**
