### PR TITLE
[Collections] Temporarily expose cellWidthAtSection: in MDCCollectionViewController.h 

### LINKED ISSUE #1351: [Collections] Client Request
From discussion with an internal client:

MDC will move the following method from private to public, with a big warning that it is temporary:
- (CGFloat)cellWidthAtSectionIndex:(NSInteger)section

MDC will implement BOOL shouldSupplementaryViewsRespectInsets on MDCCollectionViewFlowLayout.

### PR DESCRIPTION
**Pull request by felixaemiliano**
Closes #1351

### CODE REVIEW

**Comment by ianegordon** [comment]
Context:
We need to expose this method to unblock an internal client.  
Our plan is to more toward supporting self-sizing cells.

LGTM, waiting for CI.

**Review by ianegordon — APPROVED** [review]
This is a temporary measure to unblock an internal client.
LGTM.

**Comment by ianegordon** [comment]
Travis Timed-out.
Tested Locally.

**Comment by ulukaya** [comment]
Is there a timeline to have self-sizing cells to work? This is still the case right? What's the workaround till then? @ianegordon

**Pull request merged**
