### PR TITLE
[Dialogs] Call actionHandlers after the alert has been dismissed

### LINKED ISSUE #1885: [Dialogs] MDCAlertController action behavior does not match UIAlertController behavior
MDCAlertController generates a warning log if you present from an Action completion block.

Warning: Attempt to present <UIViewController: 0x7fe3a9048fd0>  on <MyCustomViewController: 0x7fe3a6c2a5c0> which is already presenting (null)

This is less than ideal.  UIAlertController does not exhibit this behavior as it invokes its action block after dismissal.  MDCAlertController should match UIAlertController's behavior.

The default behavior should be to invoke the block after dismissal, instead of before.

### PR DESCRIPTION
**Pull request by ianegordon**
Closes #1885

### CODE REVIEW

**Review by jverkoey — DISMISSED** [review]
I recall the discussion around this behavior having two points:

1. It's often beneficial to be able to initiate work immediately upon dismissing the dialog.
2. There are sometimes cases where it's desired to perform an action after the dialog has disappeared.

Can we evolve this API to match willDismiss and didDismiss conventions? This would allow a client to choose where to place the relevant logic.

**Comment by ianegordon** [comment]
MDCAlertController is intended to be a drop-in replacement for UIAlertController.

Happy to discuss evolution in another PR, but this change will better match UIAlertController and silence a runtime warning.

**Comment by jverkoey** [comment]
Am happy to defer introduction of new APIs to another PR.

---

This PR may be a significant behavior change for clients if they depended on the old behavior. What is the migration plan?

**Comment by ianegordon** [comment]
Discussed offline:
Expecting minimal impact as the presented controller will always be dismissed.
There will be a delay to the invocation of the block as we wait until after the animation completes.
We are modeling after UIAlertController, so closer matching of that behavior is desirable.
Opened #2535 to investigate preferred behavior for non-MDCAlertController use of the MDCDialogPresentationController.

**Review by jverkoey — APPROVED** [review]

**Pull request merged**
