### PR TITLE
[Tabs] Add a best-effort justification alignment setting for MDCTabBar.

### PR DESCRIPTION
**Pull request by mrhappyasthma**
This new alignment will use the Justified alignment, whenever the tabs
are small enough to fit evenly within the width of the view. And if
that's not the case, then it falls back to using Leading alignment.

Example of Justification: https://i.imgur.com/ifC4VW6.png
Example of Leading: https://i.imgur.com/stc42ds.png
Example of Leading->Justification during rotation: https://i.imgur.com/M84r8YZ.png

#### Don't forget:
- [x] Identify the component the PR relates to in brackets in the title. ```[Buttons] Updated documentation```
- [ ] Link to GitHub issues it solves. ```closes #1234```
- [x] Sign the CLA bot. You can do this once the pull request is opened.

[Contributing](./contributing/README.md#pull-requests) has more information and tips for a great
pull request.

### CODE REVIEW

**Comment by mrhappyasthma** [comment]
Clang format issues should be resolved now.

**Comment by mrhappyasthma** [comment]
Looks like some of the checks are failing for:

```
error: comparison of integers of different signs: 'typeof (self->_items.count)' (aka 'unsigned long') and 'typeof (1)' (aka 'int') [-Werror,-Wsign-compare]

  const CGFloat widthPerJustifiedItem = [self adjustedCollectionViewWidth] / MAX(_items.count, 1);
                                                                             ^~~~~~~~~~~~~~~~~~~~
```

**Comment by mrhappyasthma** [comment]
The issue has been fixed, all checks are now passing.

**Comment by romoore** [comment]
I'm a little bit cautious of this change. I think rather than adding a new type of alignment with a fallback behavior, we may want to revisit the alignment styles available to MDC-iOS Tabs in general. Currently, I believe that [Material Guidelines defines the following alignments for Tabs](https://material.io/design/components/tabs.html):

* Fixed Tabs (Full width split evenly)
* Clustered Fixed Tabs - Left (All tabs same width)
* Clustered Fixed Tabs - Right (All tabs same width)
* Clustered Fixed Tabs - Center (All tabs same width)
* Scrollable Tabs - Fixed Content (Tab sized to content)
* Scrollable Tabs - Looped Content (Tab sized to content)

**Review by ming-chu — APPROVED** [review]
--[DELETED]--

**Review by ming-chu — COMMENTED** [review]
It works perfectly, but I am not sure it is the best way to do.

**Comment by romoore** [comment]
@randallli What are your thoughts on this approach to aligning Tabs? I've opened https://github.com/material-components/material-components-ios/issues/5763 to propose improvements to Tabs' alignment as an alternative to this PR.

**Comment by randallli** [comment]
I am worried about making our component too smart and thing that we could do this in a separate object. I would prefer a delegate pattern that @romoore mentioned.

**Comment by jverkoey** [comment]
@randallli @romoore what's the next step for this PR?

**Comment by randallli** [comment]
We need to allocate time to spike on the alternative solution. If we do determine that the other option is not viable we can revisit this one.

**Pull request closed without merging**
