### PR TITLE
[TextFields] MDCTextInputControllerOutlinedTextArea border width fix

### PR DESCRIPTION
**Pull request by andrewoverton**
This PR includes the changes from @istvanp's https://github.com/material-components/material-components-ios/pull/7588 with updates to the screenshot goldens. Original PR description from https://github.com/material-components/material-components-ios/pull/7588:

Fixes border width not changing to 2 points wide when editing field (issue #7587)

## Screenshots
**Tested Device:** iPhone 6, iOS 12.3.1
### Before
[Editing](https://user-images.githubusercontent.com/179335/59697846-8f907900-91bc-11e9-9eb9-46601ecfbfe9.PNG)
[Not Editing](https://user-images.githubusercontent.com/179335/59697849-8f907900-91bc-11e9-9f94-18e84ea76d64.PNG)

### After
[Editing](https://user-images.githubusercontent.com/179335/59698057-e5fdb780-91bc-11e9-99bd-5a921c78a442.PNG)

### CODE REVIEW

**Review by bryanoltman — DISMISSED** [review]

**Comment by bryanoltman** [comment]
Hit enter too quickly – What's going on with snapshot_test_goldens/goldens_64/MDCTextFieldOutlinedControllerPreferredFontXSSnapshotTests/testTextFieldWithLongPlaceholderText_11_2@2x.png?

**Comment by andrewoverton** [comment]
@bryanoltman are you talking about https://github.com/material-components/material-components-ios/pull/9454/files?short_path=5d1dca1#diff-2fbb6de385976111f0763317701fd002? I don't know, but it doesn't look extra small to me

**Comment by bryanoltman** [comment]
It might just be another thing that came out of the call to `setNeedsLayout`. It looks like a step in the right direction at least.

**Review by bryanoltman — APPROVED** [review]

**Comment by istvanp** [comment]
@googlebot I consent.

**Pull request merged**
