### PR TITLE
[scripts] Add a squash-and-merge Chrome extension.

### PR DESCRIPTION
**Pull request by jverkoey**
This extension will automatically populate the suggested squash-and-merge description with the pull request's description.

## Before

before

## After

after

### CODE REVIEW

**Comment by jverkoey** [comment]
I've also filed a ticket with GitHub support to see if we can get an option to enable this behavior by default in GitHub, but that may take some time.

**Comment by ianegordon** [comment]
Woot!
Does it make sense to have this in its own repo?

**Review by ianegordon — APPROVED** [review]
LGTM, but please consider comment before merge.

**Comment by jverkoey** [comment]
Possibly someday, but it's presently not worth the overhead to move it out. Filed https://github.com/material-components/material-components-ios/issues/4326 to track.

**Pull request merged**
